(in-package #:autolith)

;;;; -- Asynchronous Lisp Output Tests --

(defun test-async-lisp-output-flood ()
  "Bounded capture marks discarded output without growing its storage."
  (let ((stream (application-async-lisp-output-stream-create)))
    (write-string (make-string 20000 :initial-element #\x) stream)
    (let ((text (application-async-lisp-output-text stream)))
      (test-assert (<= (length text) 16384) "async output capture is bounded")
      (test-assert (search "output truncated" text) "async output marks truncation")))
  (let* ((*application-async-lisp-output-capture-limit* 64)
         (*application-async-lisp-output-pending-limit* 8)
         (stream (application-async-lisp-output-stream-create)))
    (let ((*application-async-lisp-output-capture-limit* 512)
          (*application-async-lisp-output-pending-limit* 512))
      (write-string (make-string 256 :initial-element #\x) stream)
      (test-assert (<= (length (application-async-lisp-output-text stream)) 64)
                   "changing defaults does not change an existing stream's capacity"))))

(defun test-async-lisp-output-captures-standard-text ()
  "Capture ordinary characters, newlines, and tabs."
  (let ((stream (application-async-lisp-output-stream-create))
        (expected (format nil "one~C~Ctwo" #\Newline #\Tab)))
    (write-string expected stream)
    (test-assert (string= (application-async-lisp-output-text stream) expected)
                 "async output captures ordinary text")
    (test-assert (= (sb-gray:stream-line-column stream) 11)
                 "async output reports a useful column")
    (write-char #\Return stream)
    (test-assert (zerop (sb-gray:stream-line-column stream))
                 "carriage return resets the logical column")))

(defun test-async-lisp-output-sanitizes-control-text ()
  "Remove terminal escapes and unsafe control characters."
  (let ((stream (application-async-lisp-output-stream-create)))
    (write-string (format nil "a~C[31mb~C[0mc~Cz" #\Escape #\Escape #\Escape) stream)
    (test-assert (string= (application-async-lisp-output-text stream) "abc")
                 "async output strips terminal controls")
    (write-string (format nil "x~C~Cy~C]title" (code-char 127) (code-char 155) #\Escape)
                  stream)
    (write-char #\Escape stream)
    (write-char #\\ stream)
    (write-char #\z stream)
    (test-assert (string= (application-async-lisp-output-text stream) "abcxyz")
                 "split OSC terminators, DEL, and C1 controls cannot reach display")))

(defun test-async-lisp-output-throttles-and-flushes ()
  "Throttle live callbacks while retaining a final flush."
  (let ((chunks nil)
        (stream nil))
    (setf stream (application-async-lisp-output-stream-create
                  :output-function (lambda (chunk) (push chunk chunks))))
    (write-string "first" stream)
    (write-string "second" stream)
    (dotimes (index 10)
      (force-output stream)
      (finish-output stream))
    (test-assert (= (length chunks) 1) "async output throttles callbacks")
    (application-async-lisp-output-flush stream)
    (test-assert (= (length chunks) 2) "async output flushes final tail")
    (test-assert (search "second" (first chunks)) "async output preserves tail")
    (application-async-lisp-output-flush stream)
    (test-assert (= (length chunks) 2) "final flush does not repeat delivered output")))

(defun test-async-lisp-output-concurrent-writes ()
  "Concurrent writes produce bounded, valid captured text."
  (let ((stream (application-async-lisp-output-stream-create))
        (threads nil))
    (dotimes (index 4)
      (push (make-thread (lambda ()
                           (dotimes (count 1000)
                             (write-char #\x stream)))
                         :name (format nil "async-output-test-~D" index))
            threads))
    (dolist (thread threads)
      (join-thread thread))
    (test-assert (= (length (application-async-lisp-output-text stream)) 4000)
                 "concurrent writers retain every character within the capture limit")))
