;;; autolith-emacs-tests.el --- IDE window contracts -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)

(defun autolith-test--assert-layout (code repl shell)
  "Check the buffers and proportional window bounds of the IDE."
  (let* ((edges (window-edges (frame-root-window)))
         (left (nth 0 edges))
         (top (nth 1 edges))
         (right (nth 2 edges))
         (bottom (nth 3 edges))
         (shell-left (- right (/ (- right left) 3)))
         (repl-top (- bottom (/ (- bottom top) 4)))
         (code-window (get-buffer-window code))
         (repl-window (get-buffer-window repl))
         (shell-window (get-buffer-window shell)))
    (should (= (length (window-list nil 'nomini)) 3))
    (should (eq (selected-window) code-window))
    (should (equal (window-edges code-window)
                   (list left top shell-left repl-top)))
    (should (equal (window-edges repl-window)
                   (list left repl-top shell-left bottom)))
    (should (equal (window-edges shell-window)
                   (list shell-left top right bottom)))))

(ert-deftest autolith-ide-proportional-layout ()
  "IDE startup replaces popup placement with the requested three panes."
  (let ((code (generate-new-buffer " *autolith-test-code*"))
        (repl (generate-new-buffer " *autolith-test-repl*"))
        (shell (generate-new-buffer " *autolith-test-shell*"))
        (sly-connected-hook nil)
        (autolith--pending nil)
        (original-size (cons (frame-width) (frame-height))))
    (unwind-protect
        (save-window-excursion
          (dolist (size '((120 . 48) (96 . 36) (80 . 25)))
            (set-frame-size nil (car size) (cdr size))
            (delete-other-windows)
            (switch-to-buffer code)
            (cl-letf (((symbol-function 'autolith--require) #'ignore)
                      ((symbol-function 'agent-shell-make-agent-config)
                       (lambda (&rest arguments) arguments))
                      ((symbol-function 'sly-slynk-path)
                       (lambda () temporary-file-directory))
                      ((symbol-function 'autolith--server-variable)
                       (lambda () "AUTOLITH_EMACS_SERVER=/test/socket"))
                      ((symbol-function 'agent-shell-start)
                       (lambda (&rest _)
                         (select-window
                          (display-buffer-in-side-window
                           shell '((side . bottom)
                                   (window-parameters . ((no-delete-other-windows . t))))))
                         shell))
                      ((symbol-function 'autolith--await-port)
                       (lambda (_) (autolith--connect 12345)))
                      ((symbol-function 'sly-connect)
                       (lambda (&rest _) (run-hooks 'sly-connected-hook)))
                      ((symbol-function 'sly-current-connection)
                       (lambda () 'test-connection))
                      ((symbol-function 'sly-mrepl--find-buffer)
                       (lambda (_) repl)))
              (autolith-ide)
              (autolith-test--assert-layout code repl shell)
              (select-window (get-buffer-window repl))
              (autolith--layout code repl shell)
              (autolith-test--assert-layout code repl shell)
              (delete-file (plist-get autolith--pending :port-file)))))
      (when-let* ((port-file (plist-get autolith--pending :port-file)))
        (when (file-exists-p port-file) (delete-file port-file)))
      (set-frame-size nil (car original-size) (cdr original-size))
      (mapc #'kill-buffer (list code repl shell)))))
