(in-package #:autolith)

;;;; -- Authoritative Compaction Job State --

(-> test-compaction-job-state-bounds () null)
(defun test-compaction-job-state-bounds ()
  "Count every real outstanding job while bounding complete encoded reference rows."
  (job-completion-tests--fixture
   (lambda (parent runtime configuration)
     (declare (ignore configuration))
     (dotimes (index 24)
       (declare (ignore index))
       (job-completion-tests--start
        parent runtime :operation (lambda () (tool-success "output must not enter job context"))))
     (let* ((snapshot (task-unfinished-work-snapshot parent :limit 3))
            (rows (getf snapshot :jobs))
            (text (task-unfinished-work--encode snapshot)))
       (test-assert (task-unfinished-work-snapshot-p snapshot) "checkpoint data is portable and validated")
       (test-assert (= 24 (getf snapshot :total)) "all outstanding jobs count before request bounds")
       (test-assert (= 3 (length rows)) "row count respects the requested limit")
       (test-assert (= 21 (getf snapshot :omitted-count)) "omissions account for all unprojected work")
       (test-assert (not (search "output must not enter" text)) "result bodies never enter reference context")
       (test-assert (= 24 (length (task-continuity-inventory parent runtime)))
                    "omitted jobs are independently inspectable")
       (let* ((*task-unfinished-work-maximum-octets* 650)
              (bounded (task-unfinished-work-snapshot parent :limit 24))
              (encoded (task-unfinished-work--encode bounded)))
         (test-assert (<= (length (utf8-string-to-octets (json-encode encoded))) 650)
                      "wire-encoded evidence is bounded without slicing rows")
         (test-assert (= 24 (+ (length (getf bounded :jobs)) (getf bounded :omitted-count)))
                      "encoded-byte omissions preserve total accounting")
         (test-assert (task-unfinished-work-snapshot-p bounded) "whole bounded rows retain the checkpoint contract"))
       (let* ((*task-unfinished-work-field-limit* 40)
              (bounded (task-unfinished-work-snapshot parent :limit 24)))
         (test-assert (and (null (getf bounded :jobs)) (= 24 (getf bounded :omitted-count)))
                      "oversized references omit whole rows without truncating identities"))
       (let ((zero (task-unfinished-work-snapshot parent :limit 0)))
         (test-assert (and (= 24 (getf zero :omitted-count)) (null (getf zero :jobs)))
                      "a zero-row projection retains inspectable outstanding counts")))))
  nil)

(-> test-compaction-job-state-delivery () null)
(defun test-compaction-job-state-delivery ()
  "Derive outstanding results from authoritative receipts before and after restart."
  (job-completion-tests--fixture
   (lambda (parent runtime configuration)
     (let* ((job (job-completion-tests--start parent runtime :policy ':notify))
            (identifier (session-job-execution-identifier job))
            (before (task-unfinished-work-snapshot parent)))
       (test-assert (= 1 (getf before :total)) "notify-only terminal work awaits delivery")
       (test-assert (eq ':undelivered (getf (first (getf before :jobs)) :delivery))
                    "settled work without an owner receipt is undelivered")
       (let* ((offline (make-instance 'agent :configuration configuration
                                      :conversation (agent-conversation parent)))
              (snapshot (task-unfinished-work-snapshot offline)))
         (test-assert (= 1 (getf snapshot :total))
                      "configured agents inspect durable undelivered work without a live runtime")
         (test-assert (eq ':undelivered (getf (first (getf snapshot :jobs)) :delivery))
                      "durable ownership remains authoritative when the runtime is absent"))
       (conversation-append-summary (agent-conversation parent) "No work remains according to this summary.")
       (test-assert (= 1 (getf (task-unfinished-work-snapshot parent) :total))
                    "a model summary cannot erase authoritative outstanding work")
       (task-completion-deliver parent)
       (test-assert (task-completion--delivered-p (agent-conversation parent) identifier)
                    "fixture delivery records the exact execution receipt")
       (test-assert (zerop (getf (task-unfinished-work-snapshot parent) :total))
                    "receipt-backed results disappear from outstanding context")
       (conversation-append-summary (agent-conversation parent) "Compacted delivered work.")
       (let ((fresh (job-completion-tests--fresh-agent parent configuration)))
         (unwind-protect
              (test-assert (zerop (getf (task-unfinished-work-snapshot fresh) :total))
                           "compaction and restart retain delivery filtering without service restoration")
           (task-orchestrator-close (task-completion--runtime fresh)))))))
  nil)

(-> test-compaction-job-state-exact-owner () null)
(defun test-compaction-job-state-exact-owner ()
  "Preserve descendant visibility and exact child-conversation receipt authority."
  (job-completion-tests--fixture
   (lambda (parent runtime configuration)
     (let* ((definition (make-instance 'task-agent-definition :name "fixture" :description "fixture"
                                                            :instructions "fixture" :source ':test))
            (owner-job (task-tests--make-job runtime :identifier "owner" :parent-agent parent
                                            :definition definition :item (list :task "fixture")))
            (child (make-instance 'task-child-agent
                                 :configuration configuration :conversation (conversation-create configuration)
                                 :provider (agent-provider parent) :tool-registry (agent-tool-registry parent)
                                 :worker nil :definition definition :identity nil :depth 1
                                 :completion (make-instance 'task-completion) :orchestrator runtime :job owner-job)))
       (conversation-append-user-message (agent-conversation child) "Child-owned work.")
       (let* ((primary-job (job-completion-tests--start parent runtime))
              (child-job (job-completion-tests--start child runtime))
              (identifier (session-job-execution-identifier child-job))
              (owner (conversation-identifier (agent-conversation child)))
              (primary-view (task-unfinished-work-snapshot parent))
              (child-row (find identifier (getf primary-view :jobs)
                               :key (lambda (row) (getf row :execution-id)) :test #'equal)))
         (declare (ignore primary-job))
         (test-assert (and child-row (equal owner (getf child-row :owner-conversation))
                           (eq ':other-conversation (getf child-row :delivery)))
                      "the primary may inspect a descendant without becoming its delivery owner")
         (test-assert (= 1 (getf (task-unfinished-work-snapshot child) :total))
                      "a child sees its descendant work but not primary-owned siblings")
         (conversation-append-user-message
          (agent-conversation parent) "A receipt in the wrong owner."
          :automatic-p t :pending-input-identifier (task-completion--receipt identifier))
         (test-assert (find identifier (getf (task-unfinished-work-snapshot parent) :jobs)
                            :key (lambda (row) (getf row :execution-id)) :test #'equal)
                      "a primary receipt cannot acknowledge child-owned results")
         (task-completion-deliver child)
         (test-assert (null (find identifier (getf (task-unfinished-work-snapshot parent) :jobs)
                                 :key (lambda (row) (getf row :execution-id)) :test #'equal))
                      "the child's durable receipt filters descendant inspection too")
         (test-assert (zerop (getf (task-unfinished-work-snapshot child) :total))
                      "the exact child receipt is authoritative for its own request context")))))
  nil)

(-> test-compaction-job-state-live-unknown () null)
(defun test-compaction-job-state-live-unknown ()
  "Expose live and interrupted records without executing, delivering or reviving work."
  (job-completion-tests--fixture
   (lambda (parent runtime configuration)
     (let* ((lock (make-lock "Unfinished job gate"))
            (condition (make-condition-variable))
            (released-p nil)
            (job (task-orchestrator-start-execution-job
                  runtime parent :tool-name "compaction.fixture" :summary "running work"
                  :operation-function (lambda ()
                                        (with-lock-held (lock)
                                          (loop until released-p do (condition-wait condition lock)))
                                        (tool-success "done"))
                  :detached-p t))
            (owner (conversation-identifier (agent-conversation parent)))
            (identifier (make-identifier))
            (directory (merge-pathnames (format nil "~A/" identifier)
                                        (task--artifact-group-root configuration owner))))
       (unwind-protect
            (progn
              (task-completion-watch job parent)
              (ensure-directories-exist (merge-pathnames "continuity.sexp" directory))
              (task-continuity--write
               (merge-pathnames "continuity.sexp" directory)
               (list :version 1 :kind ':tool :job-id "interrupted" :execution-id identifier
                     :root-conversation owner :owners nil :created-at (get-universal-time)
                     :detached-p t :completion-owner-conversation owner :completion-policy ':continue))
              (let* ((before (conversation-next-sequence (agent-conversation parent)))
                     (snapshot (task-unfinished-work-snapshot parent))
                     (running (find (session-job-execution-identifier job) (getf snapshot :jobs)
                                    :key (lambda (row) (getf row :execution-id)) :test #'equal))
                     (unknown (find identifier (getf snapshot :jobs)
                                    :key (lambda (row) (getf row :execution-id)) :test #'equal)))
                (test-assert (= 2 (getf snapshot :total)) "both live and uncertain work are authoritative")
                (test-assert (and (member (getf running :status) '(:queued :running))
                                  (eq ':pending (getf running :delivery)))
                             "live queued/running work remains pending")
                (test-assert (eq ':unknown (getf unknown :status)) "interrupted work is never reported successful")
                (test-assert (= before (conversation-next-sequence (agent-conversation parent)))
                             "snapshot reads do not deliver outcomes or append records"))
              (task-continuity--write (merge-pathnames "abandon.sexp" directory)
                                      (list :decision ':abandoned :at (get-universal-time)))
              (test-assert (= 1 (getf (task-unfinished-work-snapshot parent) :total))
                           "explicitly abandoned uncertain work is settled for request context"))
         (with-lock-held (lock)
           (setf released-p t)
           (condition-notify condition))
         (session-job-await job 5)))))
  nil)

(-> test-compaction-job-state-request-context () null)
(defun test-compaction-job-state-request-context ()
  "Keep paused and terminal missions unchanged while refreshing ordinary request evidence."
  (job-completion-tests--fixture
   (lambda (parent runtime configuration)
     (job-completion-tests--start parent runtime)
     (let* ((application (mission-test--application configuration))
            (request (make-instance 'request-context :configuration configuration
                                   :conversation (agent-conversation parent) :tool-namespaces #()))
            (*task-unfinished-work-agent* parent))
       (application-mission-start application (mission-test--specification))
       (let ((goal (application-goal application)))
         (dolist (status '(:paused :cancelled :completed :failed :exhausted))
           (setf (getf goal :status) status)
           (let ((before (copy-tree goal))
                 (sequence (conversation-next-sequence (agent-conversation parent))))
             (test-assert (task-unfinished-work request) "ordinary safe boundaries offer outstanding references")
             (test-assert (equal before goal) "request projection never resets mission budgets or status")
             (test-assert (= sequence (conversation-next-sequence (agent-conversation parent)))
                          "request evidence does not append delivery acknowledgements"))))
       (setf (slot-value request 'compaction-p) t)
       (test-assert (null (task-unfinished-work request)) "side-channel summaries do not consume job context")
       (let ((*task-unfinished-work-agent* nil))
         (test-assert (null (task-unfinished-work request)) "unbound request authority contributes no guessed state")))))
  (let ((partial (make-instance 'agent)))
    (test-assert (task-unfinished-work-snapshot-p (task-unfinished-work-snapshot partial))
                 "partial agents without configured runtime have predictable empty portable state"))
  nil)
