(in-package #:autolith)

;;;; -- Declarative Context Rule Boundaries --

(-> context-rule-tests--selected (configuration conversation) list)
(defun context-rule-tests--selected (configuration conversation)
  "Return ordinary resolver contribution identities for one test request."
  (mapcar #'context-contribution-identifier
          (context-delivery-contributions
           (context-resolve-request configuration conversation #()))))

(defun test-context-rule-selection ()
  "Exercise conjunctive metadata predicates, alternatives and project/conversation scope."
  (with-test-configuration (configuration root)
    (let ((configuration (configuration-copy configuration :working-directory root))
          (*context-contributors* nil)
          (*context-rule-facts* (make-hash-table :test #'equal))
          (*context-rule-order* nil)
          (*context-resolver* (cl-llm-provider-api:make-context-resolver)))
      (let ((conversation (conversation-create configuration))
            (other (conversation-create configuration)))
        (register-context-rule
         (list :id "coding" :workspace (namestring root)
               :when '(:paths ("src/" "lib/") :languages ("common-lisp")
                       :tools ("resource.read") :namespaces ("resource")
                       :roles ("engineering") :diagnostics ("warning")
                       :events ("diagnostics"))
               :instruction "Check the changed Lisp declarations."))
        (context-rule-note conversation :paths '("src/module.lisp")
                           :languages '("common-lisp") :tools '("resource.read")
                           :namespaces '("resource") :roles '("engineering"))
        (test-assert (null (context-rule-tests--selected configuration conversation))
                     "all declared trigger fields must match")
        (context-rule-note-diagnostics
         conversation (json-object "items" (vector (json-object "severity" 2 "message" "Untrusted text"))))
        (test-assert (equal '("rule/coding") (context-rule-tests--selected configuration conversation))
                     "structured severity metadata selects ordinary advice")
        (test-assert (null (context-rule-tests--selected configuration other))
                     "trigger metadata is conversation-owned")
        (let ((request (make-instance 'request-context :configuration configuration
                                     :conversation conversation :tool-namespaces #()
                                     :compaction-p t)))
          (test-assert (not (context-rule--matches-p
                            (list :workspace (namestring root) :when '(:roles ("engineering"))) request))
                       "compaction does not select contextual advice")
          (test-assert (not (context-rule--matches-p
                            (list :workspace (namestring (merge-pathnames "other/" root))
                                  :when '(:roles ("engineering")))
                            (make-instance 'request-context :configuration configuration
                                           :conversation conversation :tool-namespaces #())))
                       "project rule scope excludes another workspace")))))
  nil)

(defun test-context-rule-validation-and-budget ()
  "Validate declarative values and exercise the existing advisory budget and replacement semantics."
  (with-test-configuration (configuration)
    (let ((*context-contributors* nil)
          (*context-rule-facts* (make-hash-table :test #'equal))
          (*context-rule-order* nil)
          (*context-resolver* (cl-llm-provider-api:make-context-resolver)))
      (let ((conversation (conversation-create configuration)))
        (dolist (rule '((:id "x" :when (:unknown ("x")) :instruction "Advice")
                        (:id "x" :when (:roles nil) :instruction "Advice")
                        (:id "x" :when (:roles ("x")) :instruction "Advice" :eval "arbitrary code")
                        (:id "x" :id "y" :when (:roles ("x")) :instruction "Advice")))
          (test-assert (handler-case (progn (register-context-rule rule) nil)
                         (context-rule-error () t))
                       "malformed declarative rule is rejected before registration"))
        (context-rule-note conversation :roles '("primary"))
        (register-context-rule '(:id "one" :when (:roles ("primary")) :instruction "First advice"))
        (register-context-rule '(:id "two" :when (:roles ("primary")) :instruction "Second advice"))
        (test-assert (= 2 (length (context-rule-tests--selected configuration conversation)))
                     "matching rules stack in the ordinary resolver")
        (let ((*context-advice-token-budget* 0))
          (test-assert (null (context-rule-tests--selected configuration conversation))
                       "rule advice honors the existing shared budget"))
        (register-context-rule '(:id "one" :when (:roles ("reviewer")) :instruction "Replacement advice"))
        (test-assert (equal '("rule/two") (context-rule-tests--selected configuration conversation))
                     "replacement uses the context contributor registry")
        (test-assert (unregister-context-rule "two") "ordinary rule unregister succeeds")
        (test-assert (null (context-rule-tests--selected configuration conversation))
                     "removed rules no longer contribute")
        (let* ((mutable (copy-seq "primary"))
               (rule (list :id "detached" :when (list :roles (list mutable))
                           :instruction "Detached rule metadata")))
          (register-context-rule rule)
          (setf (char mutable 0) #\X)
          (test-assert (equal '("rule/detached") (context-rule-tests--selected configuration conversation))
                       "caller mutation cannot change a registered predicate")))))
  nil)

(defun test-context-rule-tool-events ()
  "Capture real authorized resource operations and preserve bounded metadata lifecycle."
  (with-test-configuration (configuration root)
    (let ((configuration (configuration-copy configuration :working-directory root))
          (*context-contributors* nil)
          (*context-rule-facts* (make-hash-table :test #'equal))
          (*context-rule-order* nil)
          (*context-resolver* (cl-llm-provider-api:make-context-resolver)))
      (let* ((conversation (conversation-create configuration))
             (registry (make-default-tool-registry :configuration configuration))
             (context (make-instance 'tool-context :configuration configuration
                                    :conversation conversation :registry registry :worker nil))
             (source (merge-pathnames "module.lisp" root)))
        (with-open-file (stream source :direction ':output :if-does-not-exist ':create)
          (write-line "(values 1)" stream))
        (register-context-rule '(:id "read-lisp" :when (:languages ("common-lisp")
                                                       :tools ("resource.read")
                                                       :roles ("primary") :events ("tool-success"))
                                :instruction "Use the observed revision for edits."))
        (let ((result (tool-registry-execute-call
                       registry (json-object "namespace" "resource" "name" "read"
                                             "arguments" (json-encode (json-object "uri" "workspace:module.lisp")))
                       context)))
          (test-assert (tool-result-success-p result) "ordinary authorized read succeeds")
          (test-assert (equal '("rule/read-lisp") (context-rule-tests--selected configuration conversation))
                       "tool and source metadata select advice on the next ordinary request"))
        (let ((*context-rule-value-limit* 2))
          (context-rule-note conversation :events '("latest" "next"))
          (test-assert (equal '("latest" "next")
                              (getf (gethash (conversation-identifier conversation) *context-rule-facts*) :events))
                       "metadata retention is bounded with newest values first")
          (context-rule-note conversation :events '("latest" "fresh"))
          (test-assert (equal '("latest" "fresh")
                              (getf (gethash (conversation-identifier conversation) *context-rule-facts*) :events))
                       "repeated new metadata keeps its newest position before truncation"))
        (let ((*context-rule-conversation-limit* 1))
          (context-rule-note (conversation-create configuration) :events '("other"))
          (test-assert (= 1 (hash-table-count *context-rule-facts*))
                       "conversation metadata has bounded retention"))
        (context-rule-reset)
        (test-assert (zerop (hash-table-count *context-rule-facts*))
                     "runtime reset discards ephemeral facts without removing registrations")
        (test-assert (= 1 (length (context-contributor-registrations)))
                     "trigger reset does not remove configured rules"))))
  nil)


(defun test-context-rule-generation-and-diagnostics ()
  "Reject old-turn completions and capture structured diagnostics at the registry boundary."
  (with-test-configuration (configuration root)
    (let* ((configuration (configuration-copy configuration :working-directory root))
           (*context-contributors* nil)
           (*context-rule-facts* (make-hash-table :test #'equal))
           (*context-rule-order* nil)
           (*context-resolver* (cl-llm-provider-api:make-context-resolver))
           (conversation (conversation-create configuration))
           (registry (lsp-register-tools (make-instance 'tool-registry)))
           (agent (make-instance 'agent :configuration configuration :conversation conversation
                                       :tool-registry registry :worker nil))
           (source (merge-pathnames "diagnostics.lisp" root))
           (reset-during-query-p nil))
      (with-open-file (stream source :direction ':output :if-does-not-exist ':create)
        (write-line "(values 1)" stream))
      (context-rule-start-turn agent)
      (register-context-rule '(:id "diagnostics" :when (:diagnostics ("warning")
                                                      :tools ("lsp.diagnostics")
                                                      :events ("tool-success"))
                              :instruction "Inspect the structured warning."))
      (unwind-protect
           (let ((old-context (make-instance 'tool-context :configuration configuration
                                            :conversation conversation :registry registry :agent agent)))
             (test-call-with-function-replacements
              (list (list 'lsp-tool--call-for-file
                          (lambda (manager context path function)
                            (declare (ignore manager context path function))
                            (when reset-during-query-p
                              (context-rule-start-turn agent))
                            (json-object "items" (vector (json-object "severity" 2 "message" "payload"))))))
              (lambda ()
                (labels ((dispatch (context)
                           (tool-registry-execute-call
                            registry
                            (json-object "namespace" "lsp" "name" "diagnostics"
                                         "arguments" (json-encode (json-object "path" "diagnostics.lisp")))
                            context)))
                  (test-assert (tool-result-success-p (dispatch old-context))
                               "authorized LSP diagnostics operation succeeds")
                  (test-assert (equal '("rule/diagnostics")
                                      (context-rule-tests--selected configuration conversation))
                               "registry diagnostics select ordinary advice")
                  (setf reset-during-query-p t)
                  (test-assert (tool-result-success-p (dispatch old-context))
                               "an old operation can finish after a new turn begins")
                  (test-assert (null (context-rule-tests--selected configuration conversation))
                               "old-turn diagnostics and completion do not enter the newer turn")
                  (let* ((new-context (make-instance 'tool-context :configuration configuration
                                                     :conversation conversation :registry registry :agent agent))
                         (clone (make-instance 'tool-context :configuration configuration
                                              :conversation conversation
                                              :context-rule-generation (tool-context-rule-generation old-context))))
                    (test-assert (not (equal (tool-context-rule-generation old-context)
                                            (tool-context-rule-generation new-context)))
                                 "new contexts capture the new logical turn")
                    (test-assert (equal (tool-context-rule-generation old-context)
                                        (tool-context-rule-generation clone))
                                 "cloning does not recapture a newer generation")
                    (setf reset-during-query-p nil)
                    (test-assert (tool-result-success-p (dispatch new-context)) "new-turn diagnostics succeed")
                    (test-assert (equal '("rule/diagnostics")
                                        (context-rule-tests--selected configuration conversation))
                                 "current-turn diagnostics select advice"))))))
        (tool-registry-close-runtime-state registry))))
  nil)
