(in-package #:autolith)

;;;; -- Portable Data Transfer Behavior --

(-> test-data-transfer--write (pathname vector) pathname)
(defun test-data-transfer--write (path bytes)
  "Create one binary fixture and its parents."
  (ensure-directories-exist path)
  (data-transfer--private-write path bytes))

(-> test-data-transfer--workspace (configuration pathname) configuration)
(defun test-data-transfer--workspace (configuration directory)
  "Return a fixture configuration for a real workspace directory."
  (ensure-directories-exist directory)
  (configuration-with-working-directory configuration directory))

(-> test-data-transfer--populate (configuration pathname) list)
(defun test-data-transfer--populate (configuration root)
  "Create portable user state, including binary and referenced session assets."
  (let* ((conversation (conversation-create configuration))
         (identifier (conversation-identifier conversation))
         (image (merge-pathnames "queued.png" root))
         (object (rlm-context-intern configuration "portable context object"))
         (digest (cl-llm-provider-api:rlm-context-object-digest object))
         (memory (memory-remember configuration :title "Workspace fact" :content "remember me"))
         (global (memory-remember configuration :scope ':global :title "Linked global" :content "global guidance"))
         (forgotten (memory-remember configuration :title "Forgotten" :content "old guidance"))
         (papercut (papercut-report configuration :title "Resolved issue" :content "durable issue history"))
         (inference (conversation-create configuration :storage-root (configuration-inference-root configuration))))
    (test-conversation--write-tiny-png image)
    (conversation-append-user-message
     conversation (user-message-input-create :text "An image with history" :image-pathnames (list image)))
    (conversation-append-user-message conversation (format nil "Inspect context:~A" digest))
    (conversation-append-user-message inference (format nil "Derived from context:~A" digest))
    (memory-forget configuration (memory-identifier forgotten))
    (memory-remember configuration :identifier (memory-identifier memory)
                     :title "Workspace fact" :content "updated guidance" :source-conversation identifier)
    (papercut-assess configuration (papercut-identifier papercut)
                     :verdict ':improved :note "verified")
    (papercut-mark-closed configuration (papercut-identifier papercut) :resolution "fixed")
    (agenda-add :configuration configuration :state (agenda-load configuration)
                :text "Next task" :memory-identifiers (list (memory-identifier global)
                                                          (memory-identifier memory)))
    (plan-update configuration '((:text "Finish transfer" :status :doing)))
    ;; Asset names hold pathname metacharacters where the host allows them.
    (dolist (name (if (test-fixture-available-p *platform* ':wildcard-file-names)
                      '("plain.bin" "nested [folder]*\\dir/a\\b *?[literal].bin")
                      '("plain.bin" "nested folder/dir/a/b literal.bin")))
      (test-data-transfer--write
       (merge-pathnames (uiop:parse-native-namestring name)
                        (data-transfer--asset-root configuration ':scratchpad identifier))
       (make-array 5 :element-type '(unsigned-byte 8) :initial-contents '(0 1 127 128 255))))
    (test-data-transfer--write
     (merge-pathnames "child/result.sexp" (data-transfer--asset-root configuration ':tasks identifier))
     (data-transfer--forms-bytes (list (list :status ':success :text (format nil "context:~A" digest)))))
    (let ((pending (configuration-pending-inputs-path configuration (conversation-pathname conversation)))
          (vault (configuration-recovery-input-vault-path configuration (conversation-pathname conversation))))
      (ensure-directories-exist pending)
      (ensure-directories-exist vault)
      (snapshot-write pending
                      (list :pending-inputs :version 1 :conversation-id identifier
                            :steering (list (list :user-message-input :version 1 :text "queued image"
                                                  :image-pathnames (list (namestring image))))
                            :work nil))
      (snapshot-write vault
                      (list :recovery-input-vault :version 1 :conversation-id identifier
                            :captures (list (list :id "capture-1" :captured-at (get-universal-time)
                                                  :active-work nil :steering-in-flight nil
                                                  :steering '("recovered prompt") :work nil)))))
    (let* ((child-id (make-identifier))
           (child-root (data-transfer--child-root configuration identifier child-id))
           (child (conversation-create configuration :identifier child-id :storage-root child-root)))
      (conversation-append-user-message
       child (user-message-input-create :text "child image" :image-pathnames (list image)))
      (snapshot-write (merge-pathnames "result.sexp" child-root)
                      (list :status ':success :conversation-file (namestring (conversation-pathname child))
                            :output "child result"))
      (test-data-transfer--write
       (merge-pathnames "child.lisp" (data-transfer--asset-root configuration ':scratchpad child-id))
       (data-transfer--forms-bytes '((:child :data "kept as data"))))
      (list :conversation conversation :child child :memory memory :global global
            :forgotten forgotten :papercut papercut :digest digest :image image))))

(-> test-data-transfer--empty-and-log-boundaries () null)
(defun test-data-transfer--empty-and-log-boundaries ()
  "Exercise empty archives, native archive names, and append-only log boundaries."
  (with-test-configuration (source root)
    (dolist (workspace (list nil (configuration-working-directory source)))
      (with-test-configuration (target target-root)
        ;; Archive names carry pathname metacharacters where the host allows
        ;; them in file names, and stay plain elsewhere.
        (let* ((path (merge-pathnames
                      (uiop:parse-native-namestring
                       (if (test-fixture-available-p *platform* ':wildcard-file-names)
                           (if workspace "empty workspace [*].sexp" "empty all\\data.sexp")
                           (if workspace "empty workspace.sexp" "empty all data.sexp")))
                      root))
               (destination (merge-pathnames "relocated/" target-root)))
          (ensure-directories-exist destination)
          (data-export (uiop:native-namestring path) :workspace workspace :configuration source)
          (test-assert (zerop (getf (data-import (uiop:native-namestring path)
                                               :workspace (and workspace destination)
                                               :configuration target) :installed-files))
                       "empty all-data and workspace archives round-trip without durable writes"))))
    (let* ((memory (memory-remember source :title "Imported" :content "first appended record"))
           (path (merge-pathnames "log-boundary.sexp" root)))
      (data-export path :configuration source)
      (dolist (kind '(:empty :comment))
        (with-test-configuration (target)
          (when (eq kind ':comment)
            (memory-remember target :title "Existing" :content "local memory"))
          (let ((destination (configuration-memory-path target)))
            (ensure-directories-exist destination)
            (with-open-file (stream destination :direction ':output :if-exists ':append
                                               :if-does-not-exist ':create)
              (when (eq kind ':comment) (write-string "; unterminated final comment" stream)))
            (data-import path :configuration target)
            (test-assert (memory-find target (memory-identifier memory))
                         "empty logs gain a header and final comments cannot swallow imported records"))))))
  nil)

(-> test-data-transfer--fails-p (function &optional symbol) boolean)
(defun test-data-transfer--fails-p (function &optional (type 'data-transfer-error))
  "Return true only when FUNCTION signals the expected typed transfer failure."
  (handler-case (progn (funcall function) nil)
    (error (condition) (typep condition type))))

(-> test-data-transfer--reader-isolation () null)
(defun test-data-transfer--reader-isolation ()
  "Read archives with standard list syntax regardless of the caller's readtable."
  (with-test-configuration (configuration root)
    (let* ((archive (data-transfer--collect configuration nil))
           (path (merge-pathnames "reader.sexp" root))
           (*readtable* (copy-readtable nil))
           (called-p nil))
      (data-transfer--write-export path archive)
      (set-macro-character #\( (lambda (stream character)
                                 (declare (ignore stream character))
                                 (setf called-p t)
                                 (error 'simple-error :format-control "Ambient list reader invoked")))
      (test-assert (equalp archive (data-transfer--read path))
                   "the archive reader uses its own standard list reader")
      (test-assert (not called-p) "ambient reader macros do not run")))
  nil)

(-> test-data-transfer-roundtrip () null)
(defun test-data-transfer-roundtrip ()
  "Round-trip durable collections, replay/image assets, queued input, and native names."
  (test-data-transfer--empty-and-log-boundaries)
  (test-data-transfer--reader-isolation)
  (with-test-configuration (source root)
    (with-test-configuration (target)
      (let* ((fixture (test-data-transfer--populate source root))
             (conversation (getf fixture :conversation))
             (identifier (conversation-identifier conversation))
             (path (merge-pathnames "all.sexp" root))
             (before (data-transfer--collect source nil)))
        (let ((report (data-export path :configuration source)))
          (test-assert (= (getf report :conversations) 1) "all export includes the conversation")
          (test-assert (= (getf report :inferences) 1) "all export includes inference replay")
          (test-assert (= (getf report :memories) 3) "all export retains forgotten memory history")
          (test-assert (test-fixture-permissions-p *platform* path ':private-file)
                       "the archive is private"))
        (test-assert (plusp (getf (data-import path :configuration target) :installed-files))
                     "the first import publishes durable files")
        (let ((after (data-transfer--collect target nil)))
          (test-assert (equalp before after) "all portable records and binary assets round-trip exactly"))
        (test-assert (zerop (getf (data-import path :configuration target) :installed-files))
                     "an identical second import is idempotent")
        (let ((restored (conversation-load-by-id target identifier)))
          (test-assert (= (conversation-user-turn-count restored) 2) "conversation replay restores user turns")
          (test-assert (probe-file (conversation-log-pathname restored)) "conversation chunks are resumable"))
        (test-assert (null (memory-find target (memory-identifier (getf fixture :forgotten))))
                     "memory tombstones survive import")
        (test-assert (null (papercut-list target)) "closed papercuts do not reactivate")
        (test-assert (plan-load target) "the imported plan is found under its workspace hash")
        (test-assert (equal (nth-value 1 (rlm-context-object-find target (getf fixture :digest)))
                            "portable context object")
                     "context resource identity resolves to its exact content")
        (let* ((pending-path (configuration-pending-inputs-path target (conversation-pathname conversation)))
               (pending (snapshot-read pending-path))
               (queued (first (getf (rest pending) :steering)))
               (image-name (first (getf (rest queued) :image-pathnames))))
          (delete-file (getf fixture :image))
          (test-assert (probe-file image-name) "queued images no longer rely on the source machine")
          (test-assert (uiop:string-prefix-p (namestring (configuration-data-root target)) image-name)
                       "queued images resolve under the importing data root"))
        (test-assert (not (probe-file (configuration-auth-path target))) "authentication is outside the archive")
        (test-assert (not (probe-file (configuration-user-init-path target))) "initialization code is outside the archive"))))
  nil)

(-> test-data-transfer--state-contexts () null)
(defun test-data-transfer--state-contexts ()
  "Transfer contexts referenced only by plans, pending inputs, or recovery captures."
  (with-test-configuration (source root)
    (with-test-configuration (target)
      (let* ((conversation (conversation-create source))
             (identifier (conversation-identifier conversation))
             (texts '("Plan-only context" "Pending-only context" "Recovery-only context"))
             (digests (mapcar (lambda (text)
                               (cl-llm-provider-api:rlm-context-object-digest
                                (rlm-context-intern source text))) texts))
             (references (mapcar (lambda (digest) (format nil "context:~A" digest)) digests))
             (pending (configuration-pending-inputs-path source (conversation-pathname conversation)))
             (vault (configuration-recovery-input-vault-path source (conversation-pathname conversation)))
             (path (merge-pathnames "state-contexts.sexp" root)))
        (conversation-append-user-message conversation "Conversation with queued context references")
        (plan-update source (list (list :text (first references) :status ':doing)))
        (ensure-directories-exist pending)
        (snapshot-write pending
                        (list :pending-inputs :version 1 :conversation-id identifier
                              :steering (list (second references)) :work nil))
        (ensure-directories-exist vault)
        (snapshot-write vault
                        (list :recovery-input-vault :version 1 :conversation-id identifier
                              :captures (list (list :id "context-capture" :captured-at (get-universal-time)
                                                    :active-work nil :steering-in-flight nil
                                                    :steering (list (third references)) :work nil))))
        (data-export path :workspace (configuration-working-directory source) :configuration source)
        (data-import path :configuration target)
        (loop for digest in digests for text in texts do
          (test-assert (equal text (nth-value 1 (rlm-context-object-find target digest)))
                       "each state-only context reference resolves after workspace import")))))
  nil)

(-> test-data-transfer--stored-workspace () null)
(defun test-data-transfer--stored-workspace ()
  "Preserve archived workspace ownership when the original directory becomes a symlink."
  (with-test-fixture (':symbolic-links "workspace ownership across a symlinked directory")
    (with-test-configuration (base root)
      (with-test-configuration (target)
        (let* ((directory (merge-pathnames "original/" root))
               (source (test-data-transfer--workspace base directory))
               (replacement (merge-pathnames "replacement/" root))
               (fixture (test-data-transfer--populate source root))
               (key (workspace-directory-name directory))
               (path (merge-pathnames "original.sexp" root))
               (after-path (merge-pathnames "after-replacement.sexp" root)))
          (declare (ignore fixture))
          (data-export path :configuration source)
          (ensure-directories-exist replacement)
          (sb-posix:rmdir (uiop:native-namestring directory))
          (test-fixture-make-symbolic-link
           *platform*
           (uiop:native-namestring replacement)
           (string-right-trim "/" (uiop:native-namestring directory)))
          (unwind-protect
               (progn
                 (test-assert (plusp (getf (data-import path :configuration target) :installed-files))
                              "archive validation does not resolve stored workspace keys")
                 (data-export after-path :configuration source)
                 (test-assert (equal (list key) (getf (data-transfer--read after-path) :workspaces))
                              "collection preserves the original ownership of every durable entity")
                 (test-assert (zerop (getf (data-import after-path :configuration target) :installed-files))
                              "a changed filesystem alias does not change session identity"))
            (test-fixture-remove-link
             *platform*
             (string-right-trim "/" (uiop:native-namestring directory))))))))
  nil)

(-> test-data-transfer--native-workspaces () null)
(defun test-data-transfer--native-workspaces ()
  "Remap literal native directory arguments with and without trailing separators."
  (with-test-configuration (source root)
    (with-test-configuration (target target-root)
      (let ((path (merge-pathnames "native-workspace.sexp" root)))
        (data-export path :workspace (configuration-working-directory source) :configuration source)
        ;; Literal metacharacters appear only where the host allows them.
        (dolist (name (if (test-fixture-available-p *platform* ':wildcard-file-names)
                          '("new [repo]" "new \\repo" "new *repo")
                          '("new repo")))
          (let* ((native (uiop:native-namestring
                          (merge-pathnames (uiop:parse-native-namestring name) target-root)))
                 (directory (uiop:native-namestring
                             (data-transfer--directory-pathname
                              (uiop:parse-native-namestring native)))))
            (dolist (existing-p '(nil t))
              (when existing-p
                (ensure-directories-exist (uiop:parse-native-namestring directory)))
              (dolist (argument (list native (uiop:parse-native-namestring native) directory))
                (let ((report (data-import path :workspace argument :configuration target)))
                  (test-assert (equal directory (uiop:native-namestring
                                                 (pathname (getf report :workspace))))
                               "native workspace remapping preserves literal path characters")))))))))
  nil)

(-> test-data-transfer-workspace () null)
(defun test-data-transfer-workspace ()
  "Filter strictly by ownership, include linked globals, and relocate structured keys."
  (test-data-transfer--state-contexts)
  (test-data-transfer--stored-workspace)
  (test-data-transfer--native-workspaces)
  (with-test-configuration (base root)
    (with-test-configuration (target target-root)
      (let* ((source (test-data-transfer--workspace base (merge-pathnames "project one/" root)))
             (other (test-data-transfer--workspace base (merge-pathnames "project two/" root)))
             (fixture (test-data-transfer--populate source root))
             (foreign (conversation-create other))
             (foreign-memory (memory-remember other :title "Foreign fact" :content "not exported"))
             (destination (merge-pathnames
                           (uiop:parse-native-namestring
                            (if (test-fixture-available-p *platform* ':wildcard-file-names)
                                "new [repo]*\\name/"
                                "new repo name/"))
                           target-root))
             (path (merge-pathnames "workspace.sexp" root)))
        (conversation-append-user-message foreign "private foreign workspace history")
        (conversation-append-user-message
         (getf fixture :conversation)
         (format nil "Literal foreign id ~A and folder ~A must remain prose."
                 (conversation-identifier foreign) (configuration-working-directory source)))
        (memory-remember source :scope ':global :title "Unlinked global" :content "not a workspace dependency")
        (rlm-context-intern source "unreferenced object")
        ;; An old agenda may contain a link whose memory later moved elsewhere.
        (let* ((form (snapshot-read (configuration-agenda-path source)))
               (item (first (getf (rest (first (getf (rest form) :records))) :items))))
          (push (memory-identifier foreign-memory) (getf (rest item) :memory-ids))
          (snapshot-write (configuration-agenda-path source) form))
        (let* ((report (data-export path :workspace (configuration-working-directory source) :configuration source))
               (archive (data-transfer--read path)))
          (test-assert (= (getf report :conversations) 1) "mentions of foreign IDs do not export foreign conversations")
          (test-assert (= (getf report :memories) 3) "only owned histories and the linked global are exported")
          (test-assert (= (count ':context (getf archive :files) :key (lambda (file) (getf file :area))) 1)
                       "workspace exports include referenced context objects only")
          (test-assert (not (find (memory-identifier foreign-memory) (getf archive :memories)
                                  :key (lambda (record) (getf (rest record) :id)) :test #'equal))
                       "links cannot pull another workspace's memory into an export"))
        (ensure-directories-exist destination)
        (data-import path :workspace destination :configuration target)
        (let* ((target (configuration-with-working-directory target destination))
               (identifier (conversation-identifier (getf fixture :conversation)))
               (loaded (conversation-load-by-id target identifier))
               (archive (data-transfer--collect target nil))
               (directory (workspace-directory-name destination)))
          (test-assert (equal (conversation-origin-directory loaded) directory) "session ownership follows remapping")
          (test-assert (plan-load target) "the plan is rekeyed for the destination workspace")
          (test-assert (equal (memory-workspace (memory-find target (memory-identifier (getf fixture :memory)))) directory)
                       "workspace memories follow remapping")
          (test-assert (eq (memory-scope (memory-find target (memory-identifier (getf fixture :global)))) ':global)
                       "linked global memories keep global scope")
          (test-assert (some (lambda (text) (search "Literal foreign id" text)) (data-transfer--strings archive))
                       "transcript prose is not rewritten")
          (test-assert (not (conversation-storage-occupied-p
                            (conversation-pathname-for-id target (conversation-identifier foreign))))
                       "foreign conversations are absent from the import")
          (test-assert (zerop (getf (data-import path :workspace destination :configuration target) :installed-files))
                       "relocated imports are idempotent")))))
  nil)

(-> test-data-transfer--identity-conflicts () null)
(defun test-data-transfer--identity-conflicts ()
  "Reject cross-parent and top-level/child ID reuse before any shared assets are written."
  (with-test-configuration (source root)
    (let* ((fixture (test-data-transfer--populate source root))
           (parent-id (conversation-identifier (getf fixture :conversation)))
           (child-id (conversation-identifier (getf fixture :child)))
           (path (merge-pathnames "identity-conflicts.sexp" root)))
      (data-export path :configuration source)
      (dolist (kind '(:child-top-level :child-other-parent :top-level-child))
        (with-test-configuration (target)
          (let* ((identifier (if (eq kind ':top-level-child) parent-id child-id))
                 (owner (unless (eq kind ':child-top-level)
                          (conversation-create target :identifier "existing-parent")))
                 (storage-root (if owner
                                   (data-transfer--child-root target (conversation-identifier owner) identifier)
                                   (configuration-conversation-root target)))
                 (existing (conversation-create target :identifier identifier :storage-root storage-root)))
            (when owner
              (conversation-append-user-message owner "Existing parent history"))
            (conversation-append-user-message existing "existing identity")
            (test-data-transfer--write
             (merge-pathnames "local.bin" (data-transfer--asset-root target ':scratchpad identifier))
             (vector 1 2 3))
            (let ((before (data-transfer--collect target nil)))
              (test-assert (test-data-transfer--fails-p
                            (lambda () (data-import path :configuration target)) 'data-transfer-conflict)
                           "session IDs cannot acquire another owner through import")
              (test-assert (equalp before (data-transfer--collect target nil))
                           "identity preflight preserves existing sessions and ID-keyed assets")))))))
  nil)

(-> test-data-transfer--nested-symlinks () null)
(defun test-data-transfer--nested-symlinks ()
  "Reject symlinks below literal native directory names before reading or publishing assets."
  (with-test-fixture (':symbolic-links "symlinks below literal native directory names")
    (dolist (name (if (test-fixture-available-p *platform* ':wildcard-file-names)
                      '("[directory]" "*directory" "back\\directory")
                      '("plain directory")))
      (with-test-configuration (source root)
        (with-test-configuration (target target-root)
          (let* ((conversation (conversation-create source))
                 (identifier (conversation-identifier conversation))
                 (relative (uiop:parse-native-namestring (format nil "~A/link/file.bin" name)))
                 (source-file (merge-pathnames relative (data-transfer--asset-root source ':scratchpad identifier)))
                 (target-file (merge-pathnames relative (data-transfer--asset-root target ':scratchpad identifier)))
                 (source-link (uiop:native-namestring
                               (uiop:pathname-directory-pathname source-file)))
                 (target-link (uiop:native-namestring
                               (uiop:pathname-directory-pathname target-file)))
                 (outside (merge-pathnames "outside/" target-root))
                 (path (merge-pathnames "native-symlink.sexp" root))
                 (rejected (merge-pathnames "rejected.sexp" root)))
            (conversation-append-user-message conversation "Owned native assets")
            (test-data-transfer--write source-file (vector 1 2 3))
            (data-export path :configuration source)
            (ensure-directories-exist (uiop:pathname-parent-directory-pathname
                                      (uiop:pathname-directory-pathname target-file)))
            (ensure-directories-exist outside)
            (test-fixture-make-symbolic-link
             *platform* (uiop:native-namestring outside) (string-right-trim "/" target-link))
            (unwind-protect
                 (progn
                   (test-assert (eq ':invalid
                                    (handler-case (data-import path :configuration target)
                                      (data-transfer-error (condition)
                                        (data-transfer-error-reason condition))))
                                "import detects the actual symlink below a native directory")
                   (test-assert (and (null (conversation-list target))
                                     (null (uiop:directory-files outside)))
                                "symlink preflight publishes neither sessions nor external files"))
              (test-fixture-remove-link *platform* (string-right-trim "/" target-link)))
            (delete-file source-file)
            (sb-posix:rmdir source-link)
            (test-fixture-make-symbolic-link
             *platform* (uiop:native-namestring outside) (string-right-trim "/" source-link))
            (unwind-protect
                 (test-assert (and (test-data-transfer--fails-p
                                   (lambda () (data-export rejected :configuration source)))
                                  (not (probe-file rejected)))
                              "export rejects nested symlinks before publishing an archive")
              (test-fixture-remove-link *platform* (string-right-trim "/" source-link))))))))
  nil)

(-> test-data-transfer-rejection () null)
(defun test-data-transfer-rejection ()
  "Reject hostile syntax, traversal, bad ownership, missing references, and live conflicts."
  (test-data-transfer--identity-conflicts)
  (test-data-transfer--nested-symlinks)
  (with-test-configuration (source root)
    (with-test-configuration (target)
      (let* ((fixture (test-data-transfer--populate source root))
             (archive (data-transfer--collect source nil))
             (path (merge-pathnames "invalid.sexp" root)))
        (dolist (syntax (list "#.(error \"must not execute\")" "#S(configuration)" "#1000000000(0)"
                              (concatenate 'string (make-string 140 :initial-element #\()
                                           "nil" (make-string 140 :initial-element #\)))))
          (with-open-file (stream path :direction ':output :if-exists ':supersede)
            (write-string syntax stream))
          (test-assert (test-data-transfer--fails-p (lambda () (data-import path :configuration target)))
                       "unsafe reader syntax is rejected without publication"))
        (dolist (mutate
                 (list
                  (lambda (copy) (setf (getf copy :version) 999))
                  (lambda (copy)
                    (let* ((session (getf (first (getf copy :children)) :session))
                           (identifier (getf session :id)))
                      (setf (getf session :kind) ':inference
                            (getf copy :files)
                            (remove identifier (getf copy :files)
                                    :key (lambda (file) (getf file :owner)) :test #'equal))))
                  (lambda (copy) (setf (getf (first (getf copy :files)) :path) '(".." "escape")))
                  (lambda (copy) (setf (getf copy :workspaces) '("/unrelated/")))
                  (lambda (copy) (setf (getf copy :files)
                                       (remove ':images (getf copy :files) :key (lambda (file) (getf file :area)))))
                  (lambda (copy) (setf (getf copy :files)
                                       (remove ':input (getf copy :files) :key (lambda (file) (getf file :area)))))
                  (lambda (copy)
                    (setf (getf (rest (getf (find ':vault (getf copy :states)
                                                 :key (lambda (state) (getf state :kind))) :form)) :captures)
                          '((:id "broken"))))))
          (let ((copy (copy-tree archive)))
            (funcall mutate copy)
            (when (probe-file path) (delete-file path))
            (data-transfer--write-export path copy)
            (test-assert (test-data-transfer--fails-p (lambda () (data-import path :configuration target)))
                         "malformed archives fail before writing any durable data")
            (test-assert (null (conversation-list target)) "rejected imports publish no sessions")))
        (when (probe-file path) (delete-file path))
        (data-export path :configuration source)
        (test-assert (test-data-transfer--fails-p
                      (lambda () (data-import path :workspace (configuration-working-directory source)
                                                   :configuration target)))
                     "an all-data archive cannot be remapped as one workspace")
        (let ((legacy (copy-tree (first (getf archive :plans))))
              (legacy-path (configuration-legacy-plan-path target)))
          (setf (getf (rest legacy) :explanation) "different local plan")
          (ensure-directories-exist legacy-path)
          (snapshot-write legacy-path legacy)
          (test-assert (test-data-transfer--fails-p
                        (lambda () (data-import path :configuration target)) 'data-transfer-conflict)
                       "a legacy plan cannot be shadowed by an imported workspace plan")
          (test-assert (equal legacy (snapshot-read legacy-path)) "conflicting legacy work is preserved")
          (test-assert (null (conversation-list target)) "legacy conflicts are checked before publication")
          (delete-file legacy-path))
        (data-import path :configuration target)
        (let* ((identifier (conversation-identifier (getf fixture :conversation)))
               (lease (conversation-lease-acquire target identifier)))
          (unwind-protect
               (test-assert (test-data-transfer--fails-p
                             (lambda () (data-import path :configuration target)) 'data-transfer-conflict)
                            "import refuses a currently leased conversation")
            (conversation-lease-release lease)))
        (let ((loaded (conversation-load-by-id target (conversation-identifier (getf fixture :conversation)))))
          (conversation-append-user-message loaded "local progress")
          (test-assert (test-data-transfer--fails-p
                        (lambda () (data-import path :configuration target)) 'data-transfer-conflict)
                       "different content under an existing session identity is a conflict")))))
  nil)

(-> test-data-transfer-rollback () null)
(defun test-data-transfer-rollback ()
  "Rollback new files and merged collections after a later publication fails."
  (test-data-transfer--publication-failures)
  (with-test-configuration (source root)
    (with-test-configuration (target)
      (test-data-transfer--populate source root)
      (memory-remember target :title "Local memory" :content "preserve local history")
      (let* ((path (merge-pathnames "rollback.sexp" root))
             (memory-before (data-transfer--bytes (configuration-memory-path target)))
             (publish (symbol-function 'data-transfer--publish))
             (count 0))
        (data-export path :configuration source)
        (test-assert
         (test-call-with-function-replacements
          (list (list 'data-transfer--publish
                      (lambda (temporary destination replace-p)
                        (incf count)
                        (when (equal destination (configuration-agenda-path target))
                          (error 'simple-error :format-control "Injected publication failure"))
                        (funcall publish temporary destination replace-p))))
          (lambda () (test-data-transfer--fails-p (lambda () (data-import path :configuration target)))))
         "a publication failure is reported")
        (test-assert (> count 2) "the failure occurred after multiple publications")
        (test-assert (null (conversation-list target)) "rollback removes newly imported sessions")
        (test-assert (equalp memory-before (data-transfer--bytes (configuration-memory-path target)))
                     "rollback restores existing memory bytes exactly")
        (test-assert (not (probe-file (configuration-papercut-path target))) "rollback removes a newly imported collection")
        (test-assert (plusp (getf (data-import path :configuration target) :installed-files))
                     "a clean retry succeeds after rollback"))))
  nil)

(-> test-data-transfer--publication-failures () null)
(defun test-data-transfer--publication-failures ()
  "Exercise staging cleanup, preallocated backups, failed restoration, and external drift."
  (dolist (mode '(:cleanup :backup :restore :drift))
    (with-test-configuration (configuration root)
      (declare (ignore configuration))
      (let* ((first (merge-pathnames "first" root))
             (second (merge-pathnames "second" root))
             (third (merge-pathnames "third" root))
             (publish (symbol-function 'data-transfer--publish))
             (write (symbol-function 'data-transfer--private-write))
             (remove (symbol-function 'data-transfer--remove-staging))
             (rename (symbol-function 'uiop:rename-file-overwriting-target))
             (rollback-p nil) (removed-p nil) (write-count 0) (condition nil))
        (test-data-transfer--write first #(1))
        (test-data-transfer--write second #(2))
        (let ((writes (list (data-transfer--plan-write first #(3) root :replace-p t)
                            (data-transfer--plan-write second #(4) root :replace-p t)
                            (data-transfer--plan-write third #(5) root))))
          (test-call-with-function-replacements
           (list
            (list 'data-transfer--publish
                  (lambda (temporary target replace-p)
                    (when (equal target third)
                      (setf rollback-p t)
                      (when (eq mode ':drift)
                        (with-open-file (stream first :direction ':output :if-exists ':supersede
                                                      :element-type '(unsigned-byte 8))
                          (write-byte 9 stream)))
                      (error 'simple-error :format-control "Injected later publication failure"))
                    (funcall publish temporary target replace-p)))
            (list 'data-transfer--private-write
                  (lambda (path bytes)
                    (when (and (eq mode ':backup) (= (incf write-count) 2))
                      (error 'simple-error :format-control "Injected backup allocation failure"))
                    (funcall write path bytes)))
            (list 'data-transfer--remove-staging
                  (lambda (path)
                    (when (and (eq mode ':cleanup) (not removed-p))
                      (setf removed-p t)
                      (error 'simple-error :format-control "Injected post-link cleanup failure"))
                    (funcall remove path)))
            (list 'uiop:rename-file-overwriting-target
                  (lambda (source target)
                    (when (and (eq mode ':restore) rollback-p (equal target second))
                      (error 'simple-error :format-control "Injected restoration failure"))
                    (funcall rename source target))))
           (lambda ()
             (handler-case (data-transfer--publish-writes writes)
               (error (caught) (setf condition caught))))))
        (test-assert condition "the injected publication or backup failure is surfaced")
        (test-assert (equalp (data-transfer--bytes first) (if (eq mode ':drift) #(9) #(1)))
                     "rollback restores unaffected files and preserves detected external edits")
        (test-assert (equalp (data-transfer--bytes second) (if (eq mode ':restore) #(4) #(2)))
                     "rollback continues past a failed restoration")
        (test-assert (not (probe-file third)) "failed publication leaves no untracked new target")
        (when (member mode '(:restore :drift))
          (test-assert (typep condition 'data-transfer-rollback-error) "incomplete rollback is a distinct typed failure")
          (let ((failures (data-transfer-rollback-error-failures condition)))
            (test-assert (= (length failures) 1) "the failure identifies the exact unrestored destination")
            (test-assert (equalp (data-transfer--bytes (pathname (getf (first failures) :backup)))
                                (if (eq mode ':restore) #(2) #(1)))
                         "a preallocated private recovery copy survives failed rollback"))))))
  nil)
