(require :asdf)
(let ((setup (merge-pathnames "quicklisp/setup.lisp" (user-homedir-pathname))))
  (unless (probe-file setup)
    (let ((installer (first (uiop:command-line-arguments))))
      (unless (and installer (probe-file installer))
        (error "The Quicklisp installer is unavailable."))
      (load installer)
      (funcall (find-symbol "INSTALL" "QUICKLISP-QUICKSTART")
               :path (merge-pathnames "quicklisp/" (user-homedir-pathname))))))
