param([string]$Version,[string]$ReleaseBaseUrl=$(if($env:AUTOLITH_RELEASE_BASE_URL){$env:AUTOLITH_RELEASE_BASE_URL}else{'https://sh.lambda-symbolics.com/releases'}),[string]$ArchiveUrl,[string]$ChecksumUrl,[string]$InstallRoot,[string]$BinDirectory,[switch]$WithoutCommandLink)
$ErrorActionPreference='Stop'; Set-StrictMode -Version Latest
function Fail([string]$m){throw "Autolith installation failed: $m"}
function Fetch([string]$source,[string]$destination){if(Test-Path -LiteralPath $source -PathType Leaf){Copy-Item -LiteralPath $source -Destination $destination}else{Invoke-WebRequest -UseBasicParsing $source -OutFile $destination}}
if(-not $env:LOCALAPPDATA){Fail 'LOCALAPPDATA is not set.'}
if(-not $Version){$r=[Net.WebRequest]::Create("$ReleaseBaseUrl/latest").GetResponse();try{$Version=$r.ResponseUri.Segments[-1].Trim('/')}finally{$r.Dispose()}}
if($Version -notmatch '^v?\d+\.\d+\.\d+(?:-dev\.\d+)?$'){Fail 'version is malformed.'};if(-not $Version.StartsWith('v')){$Version="v$Version"}
$p='x86_64-windows';$name="autolith-$Version-$p";if(-not $ArchiveUrl){$ArchiveUrl="$ReleaseBaseUrl/$Version/$name.zip"};if(-not $ChecksumUrl){$ChecksumUrl="$ArchiveUrl.sha256"}
if(-not $InstallRoot){$InstallRoot=Join-Path $env:LOCALAPPDATA 'autolith\installation'};if(-not $BinDirectory){$BinDirectory=Join-Path $env:LOCALAPPDATA 'autolith\bin'}
$releases=Join-Path $InstallRoot 'releases';New-Item -ItemType Directory -Force -Path $releases|Out-Null;$temp=Join-Path $releases ".install.$PID"
try{New-Item -ItemType Directory -Force $temp|Out-Null;$zip=Join-Path $temp "$name.zip";$sum="$zip.sha256";Fetch $ArchiveUrl $zip;Fetch $ChecksumUrl $sum
 $line=@(Get-Content $sum|Where-Object{$_.Trim()});if($line.Count-ne 1-or $line[0]-notmatch '^([0-9A-Fa-f]{64})\s+\*?([^\\/]+)$'-or $Matches[2]-ne "$name.zip"){Fail 'checksum record is malformed.'};if((Get-FileHash $zip -Algorithm SHA256).Hash-ne $Matches[1]){Fail 'archive checksum is wrong.'}
 Expand-Archive $zip $temp;$src=Join-Path $temp $name;if(-not(Test-Path(Join-Path $src 'bin\autolith.cmd'))-or-not((Get-Content(Join-Path $src 'RELEASE'))-contains "platform=$p")){Fail 'archive layout is invalid.'}
 $target=Join-Path $releases "$Version-$p";if(Test-Path $target){Remove-Item -Recurse -Force $target};Move-Item $src $target;$next=Join-Path $InstallRoot ".current.$PID";Set-Content -Encoding ascii -NoNewline $next $target;Move-Item -Force $next (Join-Path $InstallRoot 'current')
 if(-not $WithoutCommandLink){New-Item -ItemType Directory -Force $BinDirectory|Out-Null;@('$ErrorActionPreference=''Stop''','$root=Split-Path -Parent $PSScriptRoot','$target=(Get-Content -Raw (Join-Path $root ''installation\current'')).Trim()','& (Join-Path $target ''bin\autolith.ps1'') @args','exit $LASTEXITCODE')|Set-Content -Encoding utf8 (Join-Path $BinDirectory 'autolith.ps1');@('@echo off','where pwsh >nul 2>nul','if %ERRORLEVEL% equ 0 (pwsh -NoProfile -ExecutionPolicy Bypass -File "%~dp0autolith.ps1" %* & exit /b %ERRORLEVEL%)','powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0autolith.ps1" %*')|Set-Content -Encoding ascii (Join-Path $BinDirectory 'autolith.cmd');$u=[Environment]::GetEnvironmentVariable('Path','User');if(-not(($u-split ';')-contains $BinDirectory)){[Environment]::SetEnvironmentVariable('Path',(($u.TrimEnd(';')+';'+$BinDirectory).TrimStart(';')),'User')}}
 "Installed Autolith $($Version.TrimStart('v'))."
}finally{if(Test-Path $temp){Remove-Item -Recurse -Force $temp}}
