(defpackage #:autolith
  (:use #:cl)
  (:shadow #:trace)
  (:import-from #:cl-resources
                #:resource
                #:resource-uri
                #:resource-observation
                #:resource-observation-uri
                #:resource-observation-revision
                #:resource-observation-content
                #:resource-observation-metadata
                #:resource-uri-parse
                #:resource-capabilities
                #:resource-observe
                #:resource-apply-operations
                #:resource-resolver
                #:resource-resolver-scheme
                #:resource-resolver-resolve
                #:resource-registry
                #:make-resource-registry
                #:resource-registry-register
                #:resource-uri-malformed
                #:resource-uri-malformed-reason
                #:resource-scheme-unknown
                #:resource-scheme-unknown-scheme
                #:resource-access-denied
                #:resource-operation-unsupported
                #:resource-operation-unsupported-operation
                #:resource-revision-stale
                #:resource-revision-stale-expected-revision
                #:resource-revision-stale-actual-revision)
  (:import-from #:lambda-debugger
                #:call-with-debugger
                #:call-with-debugger-hook
                #:condition-metadata
                #:debug-session-condition
                #:debug-session-restarts
                #:debug-session-snapshot
                #:outcome-values
                #:outcome-status
                #:outcome-condition-report
                #:outcome-restart-names
                #:outcome-selected-restart-name
                #:recovery
                #:recovery-report
                #:recovery-error
                #:safe-backtrace
                #:validate-recovery)
  (:import-from #:cl-base64
                #:base64-string-to-usb8-array
                #:base64-string-to-string
                #:usb8-array-to-base64-stream
                #:usb8-array-to-base64-string)
  (:import-from #:cl+ssl
                #:cl+ssl-error
                #:ssl-error-syscall)
  (:import-from #:sophisticated-clipboard
                #:*clipboard-backend*
                #:backend-get
                #:backend-set
                #:backend-types
                #:clipboard-backend
                #:clipboard-backend-name
                #:clipboard-copy-text
                #:sophisticated-clipboard-error
                #:terminal-clipboard-sequence)
  (:import-from #:cl-colorist
                #:color
                #:effective-color-level
                #:hex-color
                #:indexed-color
                #:make-style
                #:reset-sequence
                #:sgr-sequence)
  (:import-from #:cl-exec-sandbox
                #:external-sandbox-policy
                #:run-sandboxed
                #:sandbox-result-exit-code
                #:sandbox-result-output
                #:sandbox-result-output-truncated-p
                #:sandbox-result-timed-out-p
                #:sandbox-supported-p
                #:workspace-write-sandbox-policy)
  (:import-from #:cl-jobpond
                #:job
                #:job-aborted
                #:job-aborted-identifier
                #:job-aborted-message
                #:job-aborted-reason
                #:job-await
                #:job-cancel
                #:job-cancellation-reason
                #:job-cancellation-requested-p
                #:job-check-cancellation
                #:job-condition-report
                #:job-created-at
                #:job-deadline
                #:job-ended-at
                #:job-identifier
                #:job-index
                #:job-maximum-runtime-milliseconds
                #:job-interrupt-on-cancellation-p
                #:job-name
                #:job-not-found
                #:job-owner-identifiers
                #:job-pool
                #:job-pool-active-count
                #:job-pool-add-listener
                #:job-pool-capacity-exceeded
                #:job-pool-capacity-exceeded-limit-kind
                #:job-pool-close
                #:job-pool-closed
                #:job-pool-descendant-jobs
                #:job-pool-detach
                #:job-pool-detach-refused
                #:job-pool-detach-refused-reason
                #:job-pool-emit
                #:job-pool-error
                #:job-pool-error-message
                #:job-pool-find-job
                #:job-pool-lifecycle-state
                #:job-pool-list-jobs
                #:job-pool-live-count
                #:job-pool-maximum-batch-size
                #:job-pool-maximum-concurrency
                #:job-pool-maximum-live-jobs
                #:job-pool-maximum-runtime-milliseconds
                #:job-pool-terminal-retention-limit
                #:job-pool-queued-count
                #:job-pool-refresh
                #:job-pool-remove-listener
                #:job-pool-submit-batch
                #:job-pool-update-limits
                #:job-result
                #:job-root-identifier
                #:job-run-inline
                #:job-run-token
                #:job-snapshot
                #:job-started-at
                #:job-state
                #:job-terminal-p
                #:make-job-pool)
  (:import-from #:cl-lsp
                #:lsp-error
                #:lsp-server-configuration
                #:lsp-server-configuration-name
                #:lsp-server-configuration-arguments
                #:lsp-server-configuration-extensions
                #:lsp-server-configuration-root-markers
                #:lsp-server-configuration-initialization-options
                #:lsp-server-configuration-timeout-seconds
                #:lsp-server-configuration-disabled-p
                #:lsp-manager
                #:lsp-manager-clients
                #:lsp-manager-configurations
                #:lsp-manager-loaded-p
                #:lsp-manager-lock
                #:lsp-manager-client
                #:lsp-manager-close
                #:lsp-client
                #:lsp-client-configuration
                #:lsp-client-root
                #:lsp-client-transport
                #:lsp-client-capabilities
                #:lsp-client-diagnostics
                #:lsp-document
                #:lsp-document-path
                #:lsp-document-text
                #:lsp-read-configurations
                #:lsp-text-position
                #:lsp-client-query
                #:*lsp-query-operations*
                #:lsp-configurations-for-path
                #:lsp-manager-map-file
                #:lsp-transport
                #:lsp-transport-live-p
                #:lsp-transport-next-id
                #:lsp-transport-pending
                #:lsp-transport-open
                #:lsp-transport-request
                #:lsp-transport-close
                #:lsp-write-message)
  (:import-from #:cl-skills
                #:*skill-catalog-character-budget*
                #:*skill-file-character-limit*
                #:*skill-instruction-character-limit*
                #:skill-catalog
                #:skill-catalog-diagnostics
                #:skill-catalog-discover
                #:skill-catalog-find
                #:skill-catalog-render-error
                #:skill-catalog-render-error-minimum-required
                #:skill-catalog-skills
                #:skill-diagnostic
                #:skill-diagnostic-kind
                #:skill-diagnostic-message
                #:skill-diagnostic-pathname
                #:skill-diagnostic-root-index
                #:skill-metadata
                #:skill-metadata-cache-root
                #:skill-metadata-description
                #:skill-metadata-name
                #:skill-metadata-pathname
                #:skill-metadata-read
                #:skill-metadata-source-format
                #:skill-read-error)
  (:import-from #:cl-rfc8628
                #:*unix-epoch-universal-time*
                #:unix-time->universal-time
                #:*device-authentication-redaction-marker*
                #:*device-authentication-timeout*
                #:*rfc8628-device-slow-down-increment*
                #:credential-manager-accept-account
                #:credential-manager-primary-source
                #:credential-manager-account-id
                #:credential-manager-bootstrap-source
                #:credential-manager-provider-label
                #:credential-manager-login-hint
                #:credential-manager-credential-description
                #:credential-manager-refreshable-p
                #:credential-manager-refresh-exchange
                #:credential-manager-call-with-refresh-lock
                #:credential-manager-validate-credentials
                #:refresh-grant-credential-manager
                #:credential-manager-token-endpoint
                #:credential-manager-client-id
                #:credential-manager-refresh-parameters
                #:credential-manager-refresh-headers
                #:credential-manager-refresh-content-type
                #:credential-manager-refresh-request
                #:credential-manager-refreshed-account-ids
                #:credential-manager-validate-refresh-response
                #:credential-manager-refresh-response-credentials
                #:*refresh-json-content-type*
                #:credential-manager-import-bootstrap
                #:credential-manager-load
                #:credential-manager-refresh
                #:credential-manager-credentials
                #:credential-source-label
                #:credential-source-load
                #:credential-source-pathname
                #:credential-source-save
                #:credentials-needs-refresh-p
                #:device-authentication-client
                #:device-authentication-client-browser-function
                #:device-authentication-client-clock-function
                #:device-authentication-client-id
                #:device-authentication-client-issuer
                #:device-authentication-client-poll-function
                #:device-authentication-client-poll-timeout
                #:device-authentication-client-request-function
                #:device-authentication-client-sleep-function
                #:device-authentication-complete
                #:device-authentication-display-code
                #:device-authentication-error-code
                #:device-authentication-error-code-of-body
                #:device-authentication-error-message
                #:device-authentication-error-stage
                #:device-authentication-error-status
                #:device-authentication-fail
                #:device-authentication-invoke-request
                #:device-authentication-issuer-url
                #:device-authentication-json-request
                #:device-authentication-login
                #:device-authentication-monotonic-seconds
                #:device-authentication-open-browser
                #:device-authentication-poll-interval
                #:device-authentication-request
                #:device-authentication-request-code
                #:device-authentication-success-status-p
                #:device-authorization
                #:device-authorization-id
                #:device-authorization-poll-interval
                #:device-authorization-user-code
                #:device-authorization-verification-url
                #:jwt-expiration
                #:jwt-payload
                #:jwt-subject
                #:oauth-credentials
                #:oauth-credentials-access-token
                #:oauth-credentials-account-id
                #:oauth-credentials-expires-at
                #:oauth-credentials-id-token
                #:oauth-credentials-refresh-token
                #:oauth-credentials-secret-values
                #:oauth-credentials-source-path
                #:oauth-error-code
                #:padded-base64url
                #:redact-exact-string-value
                #:redact-exact-string-values
                #:safe-redaction-marker
                #:rfc8628-device-authentication-account-id
                #:rfc8628-device-authentication-authorization-class
                #:rfc8628-device-authentication-client
                #:rfc8628-device-authentication-client-device-code-path
                #:rfc8628-device-authentication-client-request-code-parameters
                #:rfc8628-device-authentication-client-scope
                #:rfc8628-device-authentication-client-token-path
                #:rfc8628-device-authentication-poll-for-tokens
                #:rfc8628-device-authentication-publish-credentials
                #:rfc8628-device-authentication-validate-token-response
                #:rfc8628-device-authorization
                #:rfc8628-device-authorization-expires-in
                #:rfc8628-device-authorization-issued-at)
  (:import-from #:cl-rfc8252
                #:browser-authentication-authorization-url
                #:browser-authentication-await-loopback
                #:browser-authentication-client
                #:browser-authentication-create-pkce
                #:browser-authentication-exchange-code
                #:browser-authentication-login
                #:browser-authentication-loopback-close
                #:browser-authentication-loopback-open
                #:browser-authentication-request
                #:browser-authentication-token-document)
  (:import-from #:cl-llm-provider-api
                #:copilot-auto-session-model
                #:copilot-auto-session-request
                #:copilot-base-url
                #:copilot-http-headers
                #:copilot-model-catalog
                #:copilot-model-protocol
                #:copilot-protocol-endpoint
                #:copilot-stream-headers
                #:copilot-vision-request-p
                #:*provider-maximum-streaming-retries*
                #:*provider-maximum-transient-retries*
                #:*sse-inactivity-seconds*
                #:call-with-credential-refresh
                #:call-with-streaming-retries
                #:provider-attempt-failed-event
                #:provider-attempt-failed-event-attempt
                #:provider-attempt-failed-event-condition
                #:provider-attempt-failed-event-elapsed-seconds
                #:provider-attempt-failed-event-output-received-p
                #:provider-attempt-failed-event-retryable-p
                #:provider-stream-abandoned
                #:provider-stream-abandoned-attempts
                #:sse-read-line-within-inactivity-deadline
                #:*provider-registry-error-class*
                #:model-list-decode
                #:model-spec-name
                #:model-spec-rename
                #:provider-model
                #:provider-model-context-window
                #:provider-model-context-window-specified-p
                #:provider-model-description
                #:provider-model-list-error
                #:provider-model-name
                #:provider-model-reasoning-efforts
                #:provider-name-family
                #:provider-registration
                #:provider-registration-authenticator
                #:provider-registration-declared-models
                #:provider-registration-description
                #:provider-registration-discovered-models
                #:provider-registration-endpoint
                #:provider-registration-factory
                #:provider-registration-family
                #:provider-registration-model-discovery
                #:provider-registration-model-discovery-endpoint
                #:provider-registration-model-discovery-endpoint-resolver
                #:provider-registration-models
                #:provider-registration-name
                #:provider-registration-protocol
                #:provider-registration-sequence
                #:provider-registration-source
                #:provider-registry-create
                #:provider-registry-error
                #:provider-registry-find
                #:provider-registry-for-model
                #:provider-registry-load-model-cache
                #:provider-registry-model
                #:provider-registry-model-identifiers
                #:provider-registry-refresh-models
                #:provider-registry-register
                #:provider-registry-registrations
                #:provider-registry-remove-source
                #:provider-registry-restore
                #:provider-registry-snapshot
                #:provider-registry-unregister
                #:*bounded-retry-delays*
                #:*bounded-retry-sleep-function*
                #:*character-read-sequence-window*
                #:*rlm-default-call-budget*
                #:*rlm-default-depth-budget*
                #:*rlm-default-token-budget*
                #:*sse-end-of-stream*
                #:*sse-maximum-event-characters*
                #:*sse-maximum-line-characters*
                #:*sse-read-line-function*
                #:*stream-limit-error-class*
                #:assistant-delta-event
                #:assistant-delta-event-text
                #:call-with-bounded-retries
                #:chat-completions-provider
                #:model-provider
                #:model-provider-registration
                #:provider-completed-event
                #:provider-configuration
                #:provider-consume-stream
                #:provider-credential-manager
                #:provider-event
                #:provider-family
                #:provider-item-event
                #:provider-item-event-item
                #:provider-native-compact-conversation
                #:provider-normalize-output-item
                #:provider-output-ceiling-p
                #:provider-progress-event
                #:provider-request-object
                #:provider-resample-requested-attempt
                #:provider-resample-requested-maximum-attempts
                #:provider-resample-requested-triggers
                #:provider-responses-hosted-tools
                #:provider-responses-instructions-placement
                #:provider-responses-reasoning-summary
                #:provider-responses-request-fields
                #:provider-responses-request-namespaces
                #:provider-responses-wire-effort
                #:provider-result
                #:provider-result-output-items
                #:provider-result-tool-search-calls
                #:provider-deferred-wire-tools
                #:provider-tool-search-output
                #:provider-tool-search-output-replay
                #:provider-result-response-id
                #:provider-result-tool-calls
                #:provider-result-turn-completion
                #:provider-result-turn-state
                #:provider-result-usage
                #:provider-retry-event
                #:provider-retry-event-attempt
                #:provider-retry-event-delay
                #:provider-retry-event-maximum-attempts
                #:provider-session-id
                #:provider-set-reasoning-summaries
                #:provider-stream-turn
                #:provider-wire-input-item
                #:provider-wire-protocol
                #:provider-wire-tool
                #:provider-wire-tool-name
                #:provider-wire-tools
                #:provider-with-configuration
                #:read-character-sequence
                #:read-sse-data
                #:reasoning-delta-event
                #:reasoning-delta-event-text
                #:responses-api-provider
                #:rlm-budget
                #:rlm-budget-acquire-request
                #:rlm-budget-create
                #:rlm-budget-descend
                #:rlm-budget-exhausted
                #:rlm-budget-exhausted-dimension
                #:rlm-budget-exhausted-task
                #:rlm-budget-remaining-calls
                #:rlm-budget-remaining-tokens
                #:rlm-budget-settle-output
                #:rlm-usage-billable-tokens
                #:rlm-context-object
                #:rlm-context-object-characters
                #:rlm-context-object-digest
                #:rlm-context-object-label
                #:rlm-context-object-pathname
                #:rlm-view
                #:rlm-view-error
                #:rlm-views-materialize
                #:rlm-views-render
                #:sse-read-line-characters
                #:subscription-provider
                #:gemini-generate-content-provider
                #:provider-post-event-stream
                #:provider-gemini-stream-response
                #:turn-completion
                #:provider--call-with-transport-normalization
                #:provider-signal-http-failure
                #:response-item-reasoning-summary
                #:provider-result-assistant-text
                #:response-item-assistant-text
                #:responses-standard-instructions
                #:responses-developer-message
                #:provider-unauthorized
                #:response-stream-limit-error
                #:response-stream-error
                #:provider-transport-error
                #:provider-incomplete-response
                #:provider-protocol-error
                #:provider-error
                #:openai-compatible--fallback-tool-name
                #:openai-compatible--function-call-item
                #:openai-compatible--stream-tool-states
                #:openai-compatible--choice-tool-deltas
                #:openai-compatible--tool-delta-index
                #:openai-compatible--append-tool-delta
                #:openai-compatible-tool-state
                #:openai-compatible--delta-text
                #:openai-compatible--chat-context-message
                #:openai-compatible--chat-system-message
                #:openai-compatible--chat-input-messages
                #:openai-compatible--chat-input-item
                #:openai-compatible--chat-tool-output
                #:openai-compatible--chat-function-calls
                #:openai-compatible--chat-function-call-entry
                #:openai-compatible--chat-message
                #:openai-compatible--wire-call-name
                #:openai-compatible--chat-content
                #:openai-compatible--chat-content-part
                #:openai-compatible--wire-tools
                #:openai-compatible--standalone-wire-tool
                #:openai-compatible--wire-tool
                #:openai-compatible--wire-function
                #:openai-compatible--decode-wire-tool-name
                #:openai-compatible--wire-tool-name
                #:provider--signal-event-failure
                #:provider--signal-incomplete-response
                #:provider--event-incomplete-reason
                #:provider--signal-invalid-terminal-reason
                #:provider--signal-terminal-protocol-error
                #:*provider-incomplete-terminal-reasons*
                #:provider--signal-incomplete-terminal
                #:provider--condition-string
                #:provider-rate-limit-error-p
                #:provider--retryable-event-error-code-p
                #:provider--event-request-id
                #:provider--event-response-id
                #:provider--event-error-code
                #:provider--event-error-object
                #:provider--event-response
                #:provider--decode-sse-data
                #:provider--read-sse-data
                #:provider--signal-transport-failure
                #:provider--transport-failure-message
                #:provider--signal-stream-protocol-failure
                #:provider--signal-stream-interruption
                #:provider--reasoning-summary-key
                #:provider-note-doom-loop-event
                #:normalize-response-item
                #:provider--signal-http-status-failure
                #:provider-retryable-status-p
                #:provider--http-error-message
                #:provider--error-body-detail
                #:provider--response-request-id
                #:response-header
                #:provider--sanitize-wire-value
                #:provider--sanitize-wire-string
                #:*provider-active-credential-redaction-marker*
                #:*provider-active-credential-values*
                #:*provider-credential-redaction-marker*
                #:*provider-retryable-http-statuses*
                #:*provider-error-detail-limit*
                #:*provider-retryable-event-error-codes*
                #:*provider-rate-limit-event-error-codes*
                #:*provider-wire-function-name-maximum-length*
                #:provider-wire-function-name--literal-character-p
                #:provider-wire-function-name--valid-p
                #:provider-wire-function-name--escape-sequence-p
                #:provider-wire-function-name--encode-component
                #:provider-wire-function-name--decode-component
                #:provider-wire-function-name--encode
                #:provider-wire-function-name--decode-readable
                #:provider-wire-function-name--decode-legacy
                #:provider-wire-function-name--decode
                #:provider-usage--field
                #:provider-usage--nested-field
                #:provider-usage-normalize
                #:provider-retryable-error
                #:provider-resample-requested
                #:provider-error-status
                #:provider-error-code
                #:provider-error-request-id
                #:provider-error-response-id
                #:provider-error-response
                #:provider-incomplete-response-reason
                #:*provider-error-body-deadline-seconds*
                #:provider-call-with-response-deadline
                #:provider--close-response-stream
                #:provider--drain-error-body
                #:provider--error-body-text
                #:*openai-compatible-wire-tool-name-maximum-length*
                #:provider-account-label
                #:provider-note-response-headers
                #:context-contribution
                #:context-contribution-lifetime
                #:context-contribution-class
                #:context-contribution-identifier
                #:context-contribution-instruction
                #:context-contribution-evidence
                #:context-contribution-priority
                #:context-contribution-deduplication-key
                #:context-contribution-supersedes
                #:context-contribution-conflict-group
                #:context-contribution-contributor
                #:context-contribution-source
                #:*context-contribution-identifier-limit*
                #:*context-contribution-instruction-limit*
                #:*context-mandatory-instruction-limit*
                #:*context-contribution-evidence-limit*
                #:*context-contribution-reference-limit*
                #:anthropic-messages-provider
                #:wire-request)
  (:import-from #:flexi-streams
                #:get-output-stream-sequence
                #:make-flexi-stream
                #:make-in-memory-output-stream)
  (:import-from #:clifff
                #:clifff-error
                #:clifff-error-cause
                #:clifff-error-operation
                #:clifff-error-pathname
                #:fff-library-current-p
                #:fff-library-file-name
                #:fff-library-locate
                #:make-worker
                #:worker
                #:worker-file-count
                #:worker-close
                #:worker-detach
                #:worker-process
                #:worker-request)
  (:import-from #:clinedi
                #:input-pump
                #:input-pump-call-with-exclusive-input
                #:input-pump-call-with-input-paused
                #:input-pump-live-p
                #:input-pump-paused-p
                #:input-pump-reader-thread-p
                #:input-pump-start
                #:input-pump-stop
                #:input-pump-wake
                #:make-input-pump
                #:terminal-rows
                #:terminal-columns
                #:terminal-interactive-p
                #:terminal-styled-p
                #:terminal-started-p
                #:terminal-set-dimensions
                #:terminal-standard-input-file-descriptor
                #:terminal-start
                #:terminal-stop
                #:terminal-read-event
                #:terminal-input-ready-p
                #:terminal-flush
                #:stream-terminal-input-stream
                #:stream-terminal-output-stream
                #:stream-terminal-input-file-descriptor
                #:stream-terminal-pending-input-stream
                #:stream-terminal-saved-terminal-mode
                #:terminal-read-editing-event
                #:terminal-bracketed-paste-enable-sequence
                #:terminal-bracketed-paste-disable-sequence
                #:terminal-keyboard-enhancement-enable-sequence
                #:terminal-keyboard-enhancement-disable-sequence
                #:*terminal-default-rows*
                #:*terminal-default-columns*
                #:*terminal-escape-character*
                #:*terminal-escape-delay-seconds*
                #:*terminal-unbracketed-paste-coalesce-seconds*
                #:*terminal-unbracketed-paste-maximum-characters*

                #:line-editor
                #:grapheme-previous-boundary
                #:line-editor-text
                #:line-editor-cursor
                #:line-editor-history
                #:line-editor-history-limit
                #:line-editor-set-text
                #:line-editor-clear
                #:line-editor-handle-event
                #:line-editor-move-vertical
                #:line-editor-create
                #:selector
                #:make-selector
                #:selector-items
                #:selector-selection
                #:selector-visible-count
                #:selector-move
                #:selector-set-items
                #:selector-arrange
                #:selector-handle-event
                #:enable-keyboard-enhancement
                #:disable-keyboard-enhancement
                #:enable-bracketed-paste
                #:disable-bracketed-paste
                #:semantic-prompt-marker-sequence
                #:window-title-sequence
                #:alternate-screen-enter-sequence
                #:alternate-screen-leave-sequence
                #:mouse-reporting-enable-sequence
                #:mouse-reporting-disable-sequence
                #:make-mode-tracking-output-stream
                #:mode-tracking-output-stream-restore
                #:default-color-sequence
                #:default-color-reset-sequence
                #:read-event
                #:sanitize-text
                #:text-cell-width
                #:text-cell-prefix
                #:wrap-text
                #:wrap-styled-text
                #:wrap-styled-editor-text
                #:url-at
                #:web-url-p
                #:ansi-link-urls
                #:screen-position
                #:live-region
                #:make-live-region
                #:live-region-maximum-rows
                #:live-region-row-count
                #:live-region-cursor-row
                #:live-region-cursor-column
                #:live-region-cursor-visible-p
                #:live-region-set-cursor-visible
                #:live-region-present
                #:live-region-append-and-present
                #:live-region-append
                #:live-region-suspend
                #:live-region-dismiss
                #:live-region-resize)
  (:import-from #:clingon
                #:command-arguments
                #:command-handler
                #:command-name
                #:exit-error
                #:exit-error-code
                #:getopt
                #:getopt*
                #:make-command
                #:make-option
                #:parse-command-line)
  (:import-from #:colordiff
                #:highlight-lines
                #:highlight-spans
                #:render-diff
                #:render-line-row
                #:render-source)
  (:import-from #:parenchek
                #:lisp-paren-check-path
                #:lisp-source-edit-result-content)
  (:import-from #:colorlisp
                #:language
                #:language-find
                #:native-library-path)
  (:import-from #:clinker-transcript
                #:backend-search-call-item-p
                #:chat-reasoning-item-p
                #:family-private-item-p
                #:function-call-item-p
                #:function-call-output-item
                #:item-assistant-text
                #:native-compaction-item-canonicalize
                #:native-compaction-item-p
                #:reasoning-item-p
                #:tool-search-item-p)
  (:import-from #:closer-mop
                #:class-slots
                #:slot-definition-name)
  (:import-from #:image-daemon
                #:*daemon-connect-timeout-seconds*
                #:*daemon-frame-header-character-limit*
                #:*daemon-packet-character-limit*
                #:*daemon-protocol-version*
                #:daemon-call
                #:daemon-connect
                #:daemon-packet-string
                #:daemon-error-message
                #:daemon-error-operation
                #:daemon-error-session-id
                #:daemon-random-nonce
                #:daemon-random-token
                #:daemon-read-packet
                #:daemon-read-response
                #:daemon-socket-stream
                #:daemon-write-packet
                #:eval-call
                #:eval-connect
                #:eval-endpoint
                #:eval-endpoint-create
                #:eval-endpoint-error
                #:eval-endpoint-error-reason
                #:eval-endpoint-evaluator-thread
                #:eval-endpoint-start
                #:eval-endpoint-stop
                #:eval-print-bounded
                #:legacy-session-identifier-p
                #:session-identifier-display
                #:session-identifier-normalize
                #:session-identifier-timestamp)
  (:import-from #:idsmall
                #:*random-index-function*
                #:identifier-base
                #:identifier-clear-reservations
                #:identifier-display
                #:identifier-error
                #:identifier-error-message
                #:identifier-from-seed
                #:identifier-generate
                #:identifier-normalize
                #:identifier-p
                #:identifier-reserved-p
                #:identifier-space-exhausted)
  (:import-from #:sbcl-generations
                #:*checkpoint-in-progress-p*
                #:checkpoint-backend
                #:checkpoint-single-threaded-p
                #:generation
                #:generation-compatible-p
                #:generation-coordinator-pid
                #:generation-core-pathname
                #:generation-core-probe-output
                #:generation-core-probe-record
                #:generation-core-probe-run
                #:generation-core-probe-runner
                #:generation-created-at
                #:generation-directory
                #:generation-identifier
                #:generation-manifest-pathname
                #:generation-metadata
                #:generation-record-failure
                #:generation-status
                #:generation-store
                #:generation-temporary-core-pathname
                #:make-checkpoint-backend
                #:make-generation-store
                #:make-restart-checkpoint-backend
                #:make-sbcl-core-probe-runner
                #:image-build-record
                #:image-build-record-compatible-p
                #:image-install
                #:image-installed-record
                #:image-running-build-record
                #:image-save)
  (:import-from #:sexp-config
                #:make-source-grammar
                #:read-source
                #:read-source-file
                #:sexp-config-error
                #:sexp-config-error-kind
                #:sexp-config-error-line
                #:sexp-config-error-message
                #:source-grammar
                #:validate-tree)
  (:import-from #:ironclad
                #:make-mac
                #:produce-mac
                #:random-data
                #:update-mac)
  (:import-from #:mcparen
                #:mcp-environment-binding
                #:mcp-environment-binding-target
                #:mcp-environment-binding-source
                #:mcp-transport-configuration
                #:mcp-stdio-transport-configuration
                #:mcp-stdio-configuration-command
                #:mcp-stdio-configuration-arguments
                #:mcp-stdio-configuration-directory
                #:mcp-stdio-configuration-environment-bindings
                #:mcp-http-transport-configuration
                #:mcp-http-configuration-url
                #:mcp-http-configuration-header-bindings
                #:mcp-http-configuration-connect-timeout-seconds
                #:*mcp-stdio-command-maximum-characters*
                #:*mcp-stdio-argument-maximum-characters*
                #:*mcp-stdio-maximum-arguments*
                #:*mcp-stdio-directory-maximum-characters*
                #:*mcp-environment-name-maximum-characters*
                #:*mcp-stdio-maximum-environment-bindings*
                #:*mcp-http-url-maximum-characters*
                #:*mcp-http-header-name-maximum-characters*
                #:*mcp-http-maximum-header-bindings*
                #:make-mcp-client
                #:make-mcp-stdio-transport
                #:make-mcp-streamable-http-transport
                #:mcp-call-result
                #:mcp-call-result-content
                #:mcp-call-result-error-p
                #:mcp-call-result-structured-content
                #:mcp-client
                #:mcp-client-call-tool
                #:mcp-client-close
                #:mcp-client-connect
                #:mcp-client-connection-generation
                #:mcp-client-connected-p
                #:mcp-client-detach
                #:mcp-client-get-prompt
                #:mcp-client-instructions
                #:mcp-client-list-prompts
                #:mcp-client-list-resource-templates
                #:mcp-client-list-resources
                #:mcp-client-list-tools
                #:mcp-client-read-resource
                #:mcp-client-server-capabilities
                #:mcp-client-server-info
                #:mcp-client-transport
                #:mcp-http-transport-exchange-scope-function
                #:mcp-http-transport-listener-failure
                #:mcp-http-transport-pending-session-identifier
                #:mcp-http-transport-session-identifier
                #:mcp-session-expired
                #:mcp-stdio-transport
                #:mcp-stdio-transport-ingress-projector
                #:mcp-stdio-transport-stderr-text
                #:mcp-streamable-http-transport
                #:mcp-tool
                #:mcp-tool-annotations
                #:mcp-tool-description
                #:mcp-tool-destructive-p
                #:mcp-tool-execution
                #:mcp-tool-input-schema
                #:mcp-tool-name
                #:mcp-tool-output-schema
                #:mcp-tool-read-only-p
                #:mcp-tool-raw
                #:mcp-tool-task-required-p
                #:mcp-tool-task-support
                #:mcp-tool-title
                #:mcp-transport
                #:mcp-transport-close
                #:mcp-transport-detach
                #:mcp-transport-notify
                #:mcp-transport-open
                #:mcp-transport-open-p
                #:mcp-transport-request
                #:mcp-transport-set-protocol-version
                #:mcp-server-runtime-tools-stale-p
                #:mcp-server-runtime-request-tool-refresh
                #:mcp-server-runtime-close
                #:mcp-server-runtime-detach
                #:mcp-manager-close
                #:mcp-manager-detach
                #:mcp-manager-runtime
                #:mcp-manager--connect-runtimes
                #:mcp-server-runtime-connect
                #:mcp-manager-tool-revisions
                #:mcp-server-runtime-name
                #:*mcp-maximum-retained-input-schema-bytes*
                #:*mcp-tool-discovery-restart-limit*
                #:mcp-server-runtime-client
                #:mcp-server-runtime-lock
                #:mcp-server-runtime-state
                #:mcp-server-runtime-failure
                #:mcp-server-runtime-tools
                #:mcp-server-runtime-tool-schema-bytes
                #:mcp-server-runtime-manager
                #:mcp-server-runtime-launch-environment-fingerprint
                #:mcp-server-runtime-observed-connection-generation
                #:mcp-server-runtime-tools-change-version
                #:mcp-server-runtime-tools-change-lock
                #:mcp-server-runtime-tools-discovered-version
                #:mcp-server-runtime-tools-revision
                #:mcp-manager-runtimes
                #:mcp-manager-lock)
  (:import-from #:bordeaux-threads
                #:condition-notify
                #:condition-wait
                #:current-thread
                #:destroy-thread
                #:interrupt-thread
                #:join-thread
                #:make-lock
                #:make-condition-variable
                #:make-recursive-lock
                #:make-thread
                #:thread-alive-p
                #:with-recursive-lock-held
                #:with-lock-held)
  (:import-from #:dexador.error
                #:http-request-failed
                #:response-body
                #:response-headers
                #:response-status)
  (:import-from #:quri
                #:uri
                #:uri-host
                #:uri-path
                #:uri-port
                #:uri-scheme
                #:uri-userinfo
                #:url-decode
                #:url-encode-params)
  (:import-from #:serapeum
                #:->
                #:dict)
  (:import-from #:usocket
                #:ns-error
                #:socket-error)
  (:import-from #:surgeon
                #:*definition-kinds*
                #:call-with-definition-unlocked
                #:call-with-package-unlocked
                #:call-with-restart-choice
                #:definition-form-p
                #:definition-home-package-name
                #:definition-irreversible
                #:definition-key
                #:definition-name-symbol
                #:definition-not-found
                #:definition-operator-p
                #:definition-signature
                #:definition-undo-capture
                #:definition-unsupported
                #:function-binding-restore
                #:function-binding-snapshot
                #:package-apropos
                #:package-find
                #:package-symbol-suggestions
                #:read-one-form
                #:resolve-symbol
                #:restart-choice-available
                #:restart-choice-available-choices
                #:restart-choice-available-condition
                #:source-form
                #:source-form-end
                #:source-form-form
                #:source-form-start
                #:source-read-forms
                #:surgeon-error-message
                #:symbol-defined-p
                #:symbol-definition-pathname
                #:symbol-documentation-line
                #:symbol-label
                #:symbol-lambda-list
                #:value-binding-restore)
  (:import-from #:sbcl-workers
                #:+minimum-sbcl-worker-core-size+
                #:sbcl-worker-manager-change-working-directory
                #:sbcl-worker-manager-render
                #:sbcl-worker-manager-reset
                #:sbcl-worker-manager-start
                #:sbcl-worker-manager-stop
                #:sbcl-worker-manager-stop-worker
                #:sbcl-worker-manager-worker
                #:+pristine-sbcl-worker-image-identifier+
                #:sbcl-worker
                #:sbcl-worker-change-working-directory
                #:sbcl-worker-create
                #:sbcl-worker-environment
                #:sbcl-worker-environment-context
                #:sbcl-worker-environment-create
                #:sbcl-worker-cancel-request
                #:sbcl-worker-error
                #:sbcl-worker-error-message
                #:sbcl-worker-error-operation
                #:sbcl-worker-error-pathname
                #:sbcl-worker-error-stage
                #:sbcl-worker-handle-request
                #:sbcl-worker-image
                #:sbcl-worker-image-compatible-p
                #:sbcl-worker-image-core-pathname
                #:sbcl-worker-image-error
                #:sbcl-worker-image-identifier
                #:sbcl-worker-image-load
                #:sbcl-worker-image-manifest-pathname
                #:sbcl-worker-image-note
                #:sbcl-worker-image-parent-identifier
                #:sbcl-worker-image-plausible-core-p
                #:sbcl-worker-image-publish-manifest
                #:sbcl-worker-image-scan
                #:sbcl-worker-image-staging-directory
                #:sbcl-worker-image-validate-identifier
                #:sbcl-worker-main
                #:sbcl-worker-manager-detach-inherited-processes
                #:sbcl-worker-name
                #:sbcl-worker-name-p
                #:sbcl-worker-pool
                #:sbcl-worker-pool-change-working-directory
                #:sbcl-worker-pool-create
                #:sbcl-worker-pool-environment
                #:sbcl-worker-pool-render
                #:sbcl-worker-pool-reset
                #:sbcl-worker-pool-start
                #:sbcl-worker-pool-stop
                #:sbcl-worker-pool-stop-all
                #:sbcl-worker-pool-worker
                #:sbcl-worker-request
                #:sbcl-worker-render-value
                #:sbcl-worker-reset
                #:sbcl-worker-running-p
                #:sbcl-worker-runtime-configure
                #:sbcl-worker-save-image
                #:sbcl-worker-source
                #:sbcl-worker-start
                #:sbcl-worker-stop
                #:sbcl-worker-used-image-identifier)
  (:import-from #:setinka
                #:*configuration*
                #:*configuration-default-function*
                #:*configuration-store*
                #:*settings*
                #:boolean-setting
                #:choice-setting
                #:config
                #:configuration
                #:configuration-add-listener
                #:configuration-group-values
                #:configuration-missing
                #:configuration-persist
                #:configuration-remove-listener
                #:configuration-set
                #:configuration-setting
                #:configuration-setting-list
                #:configuration-setting-source
                #:configuration-setting-value
                #:configuration-source
                #:configuration-unset
                #:configuration-validate-deferred
                #:configuration-validation-deferred-p
                #:define-setting
                #:derived-setting
                #:find-setting
                #:integer-setting
                #:make-setting-registry
                #:pathname-setting
                #:setting
                #:setting-coerce
                #:setting-default
                #:setting-default-value
                #:setting-documentation
                #:setting-environment
                #:setting-error
                #:setting-function
                #:setting-group
                #:setting-invalid
                #:setting-label
                #:setting-maximum
                #:setting-minimum
                #:setting-name
                #:setting-options
                #:setting-options-designator
                #:setting-parse
                #:setting-read-only
                #:setting-reject
                #:setting-render-value
                #:setting-scope
                #:setting-store
                #:setting-type
                #:setting-unknown
                #:setting-validate
                #:setting-visible-p
                #:settings-list
                #:store-read-values
                #:store-write-value
                #:string-setting
                #:with-configuration)
  (:import-from #:argo
                #:json-array
                #:json-boolean
                #:json-decode
                #:json-encode
                #:json-encode-utf8
                #:json-error
                #:json-false
                #:json-false-p
                #:json-get
                #:json-get-present
                #:json-object
                #:json-object-copy
                #:json-object-p
                #:json-object-source-p
                #:json-string-member-p
                #:json-string=
                #:json-true-p
                #:json-value
                #:make-json-limits)
  (:import-from #:ls-compat
                #:utf8-octets-to-string
                #:utf8-string-to-octets)
  (:import-from #:ls-compat.files
                #:file-changed
                #:file-not-utf-8
                #:file-too-large
                #:file-too-large-size
                #:publish-file
                #:publish-pathname
                #:read-file-text)
  (:import-from #:ls-compat.posix
                #:canonical-pathname
                #:current-process-id
                #:descendant-process-ids
                #:directory-names
                #:file-information
                #:file-information-change-time
                #:file-information-identity
                #:file-information-kind
                #:file-information-modification-time
                #:file-information-owned-p
                #:file-information-private-p
                #:file-information-read-only-p
                #:file-information-size
                #:file-operation-failed
                #:file-operation-failed-code
                #:file-operation-failed-reason
                #:link-file
                #:link-target-exists
                #:not-regular-file
                #:not-regular-file-kind
                #:pathname-within-p
                #:process-alive-p
                #:process-group-alive-p
                #:resolve-pathname
                #:signal-process
                #:signal-process-group
                #:stream-file-information)
  (:import-from #:ls-flock
                #:call-with-file-lock
                #:file-lock-busy
                #:file-lock-error
                #:lease-acquire
                #:lease-held-p
                #:lease-release)
  (:import-from #:sexp-store
                #:log-append
                #:log-map
                #:log-read
                #:log-write
                #:make-record
                #:plist-schema-problem
                #:plist-schema-p
                #:record-check
                #:record-property
                #:record-property-present-p
                #:record-version
                #:snapshot-read
                #:snapshot-read-record
                #:snapshot-write
                #:snapshot-write-text
                #:snapshot-write-octets
                #:store-error
                #:store-error-pathname
                #:files-publish
                #:publication-conflict
                #:publication-rollback-failed
                #:publication-rollback-failed-failures)
  (:import-from #:structlisp
                #:bounded-sequence-builder
                #:bounded-sequence-builder-maximum-count
                #:bounded-sequence-builder-overflowed-p
                #:bounded-sequence-builder-snapshot
                #:bounded-sequence-builder-try-append
                #:make-bounded-sequence-builder
                #:deque
                #:deque-append
                #:deque->list
                #:deque->vector
                #:deque-clear
                #:deque-copy
                #:deque-count
                #:deque-delete
                #:deque-empty-p
                #:deque-front
                #:deque-insert
                #:deque-maximum-count
                #:deque-maximum-weight
                #:deque-move-all
                #:deque-position-if
                #:deque-prepend
                #:deque-pop-front
                #:deque-push-front
                #:deque-push-back
                #:deque-ref
                #:deque-remove-at
                #:deque-split-at
                #:deque-total-weight
                #:make-deque
                #:fifo-cache
                #:fifo-cache-count
                #:fifo-cache-count-if
                #:fifo-cache-delete-first-if
                #:fifo-cache-find-if
                #:fifo-cache-get
                #:fifo-cache-put
                #:fifo-cache-total-weight
                #:make-fifo-cache
                #:make-priority-queue
                #:priority-queue
                #:priority-queue->list
                #:priority-queue-change-priority
                #:priority-queue-cancel
                #:priority-queue-peek
                #:priority-queue-pop
                #:priority-queue-push
                #:make-ordered-map
                #:ordered-map
                #:ordered-map-delete-if
                #:ordered-map-get
                #:ordered-map-map
                #:ordered-map-set
                #:ordered-map-values)
  (:export #:application-command
           #:application-command-aliases
           #:application-command-argument
           #:application-command-busy-action
           #:application-command-busy-behavior
           #:application-command-callable-p
           #:application-command-completion-entries
           #:application-command-completion-entry
           #:application-command-create
           #:application-command-definition-name
           #:application-command-description
           #:application-command-execute
           #:application-command-find
           #:application-command-handler
           #:application-command-invocation
           #:application-command-invocation-argument
           #:application-command-invocation-arguments
           #:application-command-invocation-command
           #:application-command-invocation-input
           #:application-command-invocation-name
           #:application-command-invocation-parse
           #:application-command-invocation-supplied-argument-count
           #:application-command-invocation-remainder
           #:application-command-lambda-list
           #:application-command-list
           #:application-command-name
           #:application-command-static-options
           #:application-command-terminal-behavior
           #:application-command-terminal-owner-p
           #:application-command-tip
           #:define-application-command
           #:main
           #:context-contributor-registrations
           #:context-status
           #:define-context-contributor
           #:make-context-contribution
           #:register-context-contributor
           #:request-context-compaction-p
           #:request-context-configuration
           #:request-context-conversation
           #:request-context-goal-context
           #:request-context-latest-user-text
           #:request-context-tool-namespaces
           #:register-application-command
           #:release-server-main
           #:run-tests
           #:unregister-application-command
           #:unregister-context-contributor
           #:vault-contents
           #:*structural-program*
           #:structural-register-tools
           #:structural-register-default-tools
           #:*debug-adapter-program*
           #:*debug-adapter-arguments*
           #:debug-register-tools
           #:debug-register-default-tools
           #:register-context-rule
           #:unregister-context-rule
           #:context-rule-note
           #:worker-tool-call
           #:worker-tool-context
           #:worker-main))

(in-package #:autolith)
