(defpackage #:autolith
  (:use #:cl)
  (:shadow #:trace)
  (:import-from #:cl-base64
                #:base64-string-to-usb8-array
                #:base64-string-to-string
                #:usb8-array-to-base64-string)
  (:import-from #:cl+ssl
                #:cl+ssl-error
                #:ssl-error-syscall)
  (:import-from #:cl-colorist
                #:effective-color-level
                #:indexed-color
                #:make-style
                #:reset-sequence
                #:sgr-sequence)
  (:import-from #:cl-exec-sandbox
                #:external-sandbox-policy
                #:run-sandboxed
                #:sandbox-result-exit-code
                #:sandbox-result-output
                #:sandbox-result-output-truncated-p
                #:sandbox-result-timed-out-p
                #:workspace-write-sandbox-policy)
  (:import-from #:cl-jobpond
                #:job
                #:job-aborted
                #:job-aborted-identifier
                #:job-aborted-message
                #:job-aborted-reason
                #:job-await
                #:job-cancel
                #:job-cancellation-reason
                #:job-cancellation-requested-p
                #:job-check-cancellation
                #:job-condition-report
                #:job-created-at
                #:job-deadline
                #:job-ended-at
                #:job-identifier
                #:job-index
                #:job-maximum-runtime-milliseconds
                #:job-name
                #:job-not-found
                #:job-owner-identifiers
                #:job-pool
                #:job-pool-active-count
                #:job-pool-add-listener
                #:job-pool-capacity-exceeded
                #:job-pool-capacity-exceeded-limit-kind
                #:job-pool-close
                #:job-pool-closed
                #:job-pool-descendant-jobs
                #:job-pool-detach
                #:job-pool-detach-refused
                #:job-pool-detach-refused-reason
                #:job-pool-emit
                #:job-pool-error
                #:job-pool-error-message
                #:job-pool-find-job
                #:job-pool-lifecycle-state
                #:job-pool-list-jobs
                #:job-pool-live-count
                #:job-pool-maximum-batch-size
                #:job-pool-maximum-concurrency
                #:job-pool-maximum-live-jobs
                #:job-pool-maximum-runtime-milliseconds
                #:job-pool-queued-count
                #:job-pool-refresh
                #:job-pool-remove-listener
                #:job-pool-submit-batch
                #:job-pool-update-limits
                #:job-result
                #:job-root-identifier
                #:job-run-inline
                #:job-run-token
                #:job-snapshot
                #:job-started-at
                #:job-state
                #:job-terminal-p
                #:make-job-pool)
  (:import-from #:flexi-streams
                #:get-output-stream-sequence
                #:make-flexi-stream
                #:make-in-memory-output-stream)
  (:import-from #:clifff
                #:clifff-error
                #:clifff-error-cause
                #:clifff-error-operation
                #:clifff-error-pathname
                #:make-worker
                #:worker
                #:worker-close
                #:worker-detach
                #:worker-process
                #:worker-request)
  (:import-from #:clinedi
                #:line-editor
                #:grapheme-previous-boundary
                #:line-editor-text
                #:line-editor-cursor
                #:line-editor-history
                #:line-editor-set-text
                #:line-editor-clear
                #:line-editor-handle-event
                #:line-editor-move-vertical
                #:line-editor-create
                #:selector
                #:make-selector
                #:selector-items
                #:selector-selection
                #:selector-visible-count
                #:selector-move
                #:selector-set-items
                #:selector-arrange
                #:selector-handle-event
                #:enable-keyboard-enhancement
                #:disable-keyboard-enhancement
                #:enable-bracketed-paste
                #:disable-bracketed-paste
                #:semantic-prompt-marker-sequence
                #:read-event
                #:sanitize-text
                #:text-cell-width
                #:text-cell-prefix
                #:wrap-text
                #:wrap-styled-text
                #:wrap-styled-editor-text
                #:screen-position
                #:live-region
                #:make-live-region
                #:live-region-maximum-rows
                #:live-region-row-count
                #:live-region-cursor-row
                #:live-region-cursor-column
                #:live-region-cursor-visible-p
                #:live-region-set-cursor-visible
                #:live-region-present
                #:live-region-append-and-present
                #:live-region-append
                #:live-region-suspend
                #:live-region-dismiss
                #:live-region-resize)
  (:import-from #:clingon
                #:command-arguments
                #:command-handler
                #:command-name
                #:exit-error
                #:exit-error-code
                #:getopt
                #:getopt*
                #:make-command
                #:make-option
                #:parse-command-line)
  (:import-from #:colordiff
                #:highlight-lines
                #:highlight-spans
                #:render-diff)
  (:import-from #:parenchek
                #:lisp-paren-check-path
                #:lisp-source-edit-result-content)
  (:import-from #:colorlisp
                #:language
                #:language-find
                #:native-library-path)
  (:import-from #:closer-mop
                #:class-slots
                #:slot-definition-name)
  (:import-from #:idsmall
                #:*random-index-function*
                #:identifier-base
                #:identifier-clear-reservations
                #:identifier-display
                #:identifier-error
                #:identifier-error-message
                #:identifier-from-seed
                #:identifier-generate
                #:identifier-normalize
                #:identifier-p
                #:identifier-reserved-p
                #:identifier-space-exhausted)
  (:import-from #:sbcl-generations
                #:*checkpoint-in-progress-p*
                #:checkpoint-backend
                #:checkpoint-single-threaded-p
                #:generation
                #:generation-compatible-p
                #:generation-coordinator-pid
                #:generation-core-pathname
                #:generation-core-probe-output
                #:generation-core-probe-record
                #:generation-core-probe-run
                #:generation-core-probe-runner
                #:generation-created-at
                #:generation-directory
                #:generation-identifier
                #:generation-manifest-pathname
                #:generation-metadata
                #:generation-record-failure
                #:generation-status
                #:generation-store
                #:generation-temporary-core-pathname
                #:make-checkpoint-backend
                #:make-generation-store
                #:make-sbcl-core-probe-runner)
  (:import-from #:sexp-config
                #:make-source-grammar
                #:read-source
                #:sexp-config-error
                #:sexp-config-error-kind
                #:sexp-config-error-line
                #:sexp-config-error-message
                #:source-grammar
                #:validate-tree)
  (:import-from #:ironclad
                #:digest-sequence
                #:make-mac
                #:produce-mac
                #:random-data
                #:update-mac)
  (:import-from #:mcparen
                #:make-mcp-client
                #:make-mcp-stdio-transport
                #:make-mcp-streamable-http-transport
                #:mcp-call-result
                #:mcp-call-result-content
                #:mcp-call-result-error-p
                #:mcp-call-result-structured-content
                #:mcp-client
                #:mcp-client-call-tool
                #:mcp-client-close
                #:mcp-client-connect
                #:mcp-client-connection-generation
                #:mcp-client-connected-p
                #:mcp-client-detach
                #:mcp-client-get-prompt
                #:mcp-client-instructions
                #:mcp-client-list-prompts
                #:mcp-client-list-resource-templates
                #:mcp-client-list-resources
                #:mcp-client-list-tools
                #:mcp-client-read-resource
                #:mcp-client-server-capabilities
                #:mcp-client-server-info
                #:mcp-client-transport
                #:mcp-http-transport-exchange-scope-function
                #:mcp-http-transport-listener-failure
                #:mcp-http-transport-pending-session-identifier
                #:mcp-http-transport-session-identifier
                #:mcp-session-expired
                #:mcp-stdio-transport
                #:mcp-stdio-transport-ingress-projector
                #:mcp-stdio-transport-stderr-text
                #:mcp-streamable-http-transport
                #:mcp-tool
                #:mcp-tool-annotations
                #:mcp-tool-description
                #:mcp-tool-destructive-p
                #:mcp-tool-execution
                #:mcp-tool-input-schema
                #:mcp-tool-name
                #:mcp-tool-output-schema
                #:mcp-tool-read-only-p
                #:mcp-tool-raw
                #:mcp-tool-task-required-p
                #:mcp-tool-task-support
                #:mcp-tool-title
                #:mcp-transport
                #:mcp-transport-close
                #:mcp-transport-detach
                #:mcp-transport-notify
                #:mcp-transport-open
                #:mcp-transport-open-p
                #:mcp-transport-request
                #:mcp-transport-set-protocol-version)
  (:import-from #:bordeaux-threads
                #:condition-notify
                #:condition-wait
                #:current-thread
                #:interrupt-thread
                #:join-thread
                #:make-lock
                #:make-condition-variable
                #:make-recursive-lock
                #:make-thread
                #:thread-alive-p
                #:with-recursive-lock-held
                #:with-lock-held)
  (:import-from #:dexador.error
                #:http-request-failed
                #:response-body
                #:response-headers
                #:response-status)
  (:import-from #:opticl
                #:8-bit-gray-alpha-image
                #:8-bit-gray-image
                #:8-bit-rgb-image
                #:8-bit-rgba-image
                #:coerce-image
                #:gray-alpha-image
                #:gray-image
                #:read-image-stream
                #:resize-image
                #:rgb-image
                #:rgba-image
                #:write-png-file)
  (:import-from #:quri
                #:ip-addr-p
                #:ip-addr=
                #:ipv4-addr-p
                #:ipv6-addr-p
                #:uri
                #:uri-host
                #:uri-path
                #:uri-port
                #:uri-scheme
                #:url-decode
                #:url-encode-params)
  (:import-from #:serapeum
                #:->
                #:dict)
  (:import-from #:usocket
                #:ns-error
                #:socket-error)
  (:import-from #:sbcl-workers
                #:+minimum-sbcl-worker-core-size+
                #:+pristine-sbcl-worker-image-identifier+
                #:sbcl-worker
                #:sbcl-worker-change-working-directory
                #:sbcl-worker-create
                #:sbcl-worker-environment
                #:sbcl-worker-environment-context
                #:sbcl-worker-environment-create
                #:sbcl-worker-cancel-request
                #:sbcl-worker-error
                #:sbcl-worker-error-message
                #:sbcl-worker-error-operation
                #:sbcl-worker-error-pathname
                #:sbcl-worker-error-stage
                #:sbcl-worker-handle-request
                #:sbcl-worker-image
                #:sbcl-worker-image-compatible-p
                #:sbcl-worker-image-core-pathname
                #:sbcl-worker-image-error
                #:sbcl-worker-image-identifier
                #:sbcl-worker-image-load
                #:sbcl-worker-image-manifest-pathname
                #:sbcl-worker-image-note
                #:sbcl-worker-image-parent-identifier
                #:sbcl-worker-image-plausible-core-p
                #:sbcl-worker-image-publish-manifest
                #:sbcl-worker-image-scan
                #:sbcl-worker-image-staging-directory
                #:sbcl-worker-image-validate-identifier
                #:sbcl-worker-main
                #:sbcl-worker-manager-detach-inherited-processes
                #:sbcl-worker-name
                #:sbcl-worker-name-p
                #:sbcl-worker-pool
                #:sbcl-worker-pool-change-working-directory
                #:sbcl-worker-pool-create
                #:sbcl-worker-pool-environment
                #:sbcl-worker-pool-render
                #:sbcl-worker-pool-reset
                #:sbcl-worker-pool-start
                #:sbcl-worker-pool-stop
                #:sbcl-worker-pool-stop-all
                #:sbcl-worker-pool-worker
                #:sbcl-worker-request
                #:sbcl-worker-render-value
                #:sbcl-worker-reset
                #:sbcl-worker-running-p
                #:sbcl-worker-runtime-configure
                #:sbcl-worker-save-image
                #:sbcl-worker-source
                #:sbcl-worker-start
                #:sbcl-worker-stop
                #:sbcl-worker-used-image-identifier)
  (:import-from #:sexp-store
                #:log-append
                #:log-map
                #:log-read
                #:snapshot-read
                #:snapshot-write
                #:store-error)
  (:import-from #:structlisp
                #:deque
                #:deque-append
                #:deque->list
                #:deque->vector
                #:deque-clear
                #:deque-copy
                #:deque-count
                #:deque-delete
                #:deque-empty-p
                #:deque-front
                #:deque-insert
                #:deque-maximum-count
                #:deque-maximum-weight
                #:deque-move-all
                #:deque-move-if
                #:deque-position-if
                #:deque-prepend
                #:deque-pop-front
                #:deque-push-front
                #:deque-push-back
                #:deque-ref
                #:deque-remove-at
                #:deque-split-at
                #:deque-total-weight
                #:make-deque
                #:fifo-cache
                #:fifo-cache-count
                #:fifo-cache-count-if
                #:fifo-cache-delete-first-if
                #:fifo-cache-find-if
                #:fifo-cache-get
                #:fifo-cache-put
                #:fifo-cache-total-weight
                #:make-fifo-cache
                #:make-priority-queue
                #:priority-queue
                #:priority-queue->list
                #:priority-queue-change-priority
                #:priority-queue-cancel
                #:priority-queue-peek
                #:priority-queue-pop
                #:priority-queue-push
                #:make-ordered-map
                #:ordered-map
                #:ordered-map-delete-if
                #:ordered-map-get
                #:ordered-map-map
                #:ordered-map-set
                #:ordered-map-values)
  (:import-from #:yason
                #:false)
  (:export #:application-command
           #:application-command-aliases
           #:application-command-argument
           #:application-command-busy-action
           #:application-command-busy-behavior
           #:application-command-call-lambda-list
           #:application-command-completion-entries
           #:application-command-completion-entry
           #:application-command-create
           #:application-command-definition-name
           #:application-command-description
           #:application-command-execute
           #:application-command-find
           #:application-command-handler
           #:application-command-invocation
           #:application-command-invocation-argument
           #:application-command-invocation-arguments
           #:application-command-invocation-command
           #:application-command-invocation-input
           #:application-command-invocation-name
           #:application-command-invocation-parse
           #:application-command-invocation-supplied-argument-count
           #:application-command-invocation-remainder
           #:application-command-list
           #:application-command-name
           #:application-command-semantic-handler-p
           #:application-command-slash-argument-mode
           #:application-command-terminal-behavior
           #:application-command-terminal-owner-p
           #:application-command-tip
           #:define-application-command
           #:main
           #:context-contributor-registrations
           #:context-status
           #:define-context-contributor
           #:make-context-contribution
           #:register-context-contributor
           #:request-context-compaction-p
           #:request-context-configuration
           #:request-context-conversation
           #:request-context-goal-context
           #:request-context-latest-user-text
           #:request-context-tool-namespaces
           #:register-application-command
           #:release-server-main
           #:run-tests
           #:unregister-application-command
           #:unregister-context-contributor
           #:worker-main))

(in-package #:autolith)
